README.md
deployment-details.md
setup.py
tc-admin.py

This sets up a little bit of infrastructure for managing "projects" within this deployment of TC.  The data at the top would likely move to YAML files eventually.  The use of JSON-e may not be great :)

Manage some basic stuff - early days

---

README.md
generate/repo_access.py

..and add a project to each repo_access stanza.

Add some description of conventions

---

config/projects.yml

WIP: currently using my fork of this project to test
the first commit shows the state this PR will be reverted to prior to merge

Bug 1574658: Add bors-ng project and ci worker-pool

---

generate/grants.py
generate/projects.py
setup.py

This involves the loader's load method becoming async.

update to tc-admin 2.0.0

---

setup.py

In particular, this gets us the ability to manage clients

upgrade tc-admin to 2.1.0

---

misc/aws-worker-vpc-setup.sh

- creates an internet gateway and attaches it to the vpc
- creates a route for internet bound traffic from the vpc through the internet gateway

move aws-worker-vpc-setup to misc dir, add internet gateway + route creation

---

README.md
config/grants.yml
config/projects.yml
generate/__init__.py
generate/grants.py
generate/login_identity.py
generate/projects.py
tc-admin.py

* Add servo
* Add a `repo-admin:..` utility role to grant admin access to repos
* Add support for "externally managed" projects, where the project admins are responsible for all or most of the resources in the project.

Bug 1574648 - add a servo project, plus machinery

---

generate/workers.py

WIP so far until I get an image that works -- this one starts but doesn't call registerWorker.
I'm not sure the workerConfig is correct - I'm not sure if workerConfig requires a `genericWorker` subkey.
https://bugzilla.mozilla.org/show_bug.cgi?id=1591243

Bug 1591243 - configure win2012r2, generic-worker, AWS images

---

config/projects.yml

Bug 1574648 - add workerpools for servo

---

config/grants.yml

See https://github.com/taskcluster/taskcluster/pull/1418.

use worker-manager:manage-worker-pool:.. scope

---

config/grants.yml
config/projects.yml
generate/workers.py

- also adds `purge-cache` scope for project admins

add deepspeech project and win-b worker

---

config/grants.yml

Grant project admins worker-related scopes (workerGroupId proj-<..>)

---

config/projects.yml

Add new admin team for relman

---

config/grants.yml

..and reorganize the stanza a little

Grant rerun, cancel, etc. to firefoxreality

---

README.md
config/projects.yml
generate/__init__.py
generate/projects.py
setup.py

Most of the interesting stuff here is stolen from @djmitche. It adds a few more secrets to be managed and also makes a secret for each workerpool.  I'm particulary interested in seeing if this diff looks good before I apply it. In particular it removes all `worker-type` secrets and some others that look to be unused copy-pastes. I also moved `project/webrender-ci/wrupdater-github-token` to 
`project/webrender/wrupdater-github-token` in order to be inside the proper namespace. Is that a good location for it and should I make the PR to update webrender?
Anything else anyone sees that should change?
```diff
- Secret=garbage/servo/wpt-test
- Secret=project/taskcluster/proj-deepspeech/worker-types/ssh-keys/deepspeech-win
- Secret=project/taskcluster/proj-deepspeech/worker-types/ssh-keys/deepspe …
```

Manage secrets

---

config/projects.yml

See [bug 1575648](https://bugzil.la/1575648) for context.
Thanks!

Bug 1575648 - indexes for webrender CI tasks

---

config/projects.yml

Add privileged to relman worker

---

config/projects.yml

This should be a pretty good match to the aws types they have now

Add relman workerpools

---

config/projects.yml

- per conversation with hexcles in irc

allow wpt/ci privileged docker-worker

---

config/projects.yml

Upgrade deepspeech windows workers to generic-worker 16.5.5

---

config/projects.yml

```diff
--- current                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
+++ generated
@@ -528,16 +528,37 @@ Role=hook-id:project-misc/jcristau-fx-release-metrics:
scopes:
- queue:create-task:highest:proj-misc/ci
- queue:route:index.project.misc.jcristau.*
- queue:route:notify.email.jcristau@mozilla.com.*
- queue:scheduler-id:-
+ …
```

Bug 1595417 Add scopes for bugbug hooks

---

config/projects.yml

Cleanup credentials for docker-worker CI

---

config/projects.yml

Follow-up to https://github.com/mozilla/community-tc-config/pull/114.

Remove extraneous 'assume:' from bugbug build role

---

config/projects.yml

Admins are the mozilla-l10n/Core group, currently consisting of me, Matjaz, and flod.

Create a project for l10n tasks on the community taskcluster.

---

config/projects.yml

See taskcluster/taskcluster#1859.

allow team 'smoketesters' to run smoketests

---

config/projects.yml

- adds monopacker secrets for image baking

add monopacker secrets and grants

---

config/projects.yml
generate/projects.py

@imbstack does this fit what you were looking for?

Bug 1595182 - allow externallyManaged to specify specific resources

---

config/projects.yml

And allow notifying on any bugbug.* route.

Add scopes to handle a new bugbug hook

---

config/grants.yml
generate/grants.py

… in order to work around current tc-github limitations.

Allow GitHub task to forward the 'statuses' and 'checks' routes

---

config/projects.yml

This is just for running simple CI for now.

Add MozillaSecurity repo to misc project.

---

config/projects.yml

Follow on from #150. I saw these secrets have been created, so this should protect them from deletion by tc-admin.
CC @jschwartzentruber

Add fuzzing secrets

---

config/projects.yml

- CI secret
- ~docker privileged mode~
- simple hook

Setup initial CI for Fuzzing

---

config/projects.yml

Add missing wildcard to MozillaSecurity:fuzzing-tc repo rules

---

config/aws.yml
generate/aws.yml
generate/workers.py

This file will be used by the [fuzzing team decision task](https://github.com/MozillaSecurity/fuzzing-tc) to build worker pools
I checked that this PR did *not* change anything when running `tc-admin diff` in comparison to current's master state.

Move aws constants in dedicated YAML file.

---

generate/workers.py

Fixes #154.
The issue was that, when run `--without-secrets`, it was generating a Secret instance for *every* worker pool, even though some worker pools do not actually define one when run with `--with-secrets`.  So the diff indicated it wanted to add more secrets, when really it didn't.

Consistently generate secrets for workers regardless of secrets mode

---

imagesets/deepspeech-win2012r2/bootstrap.ps1
imagesets/firefoxreality-1-win10-64/bootstrap.ps1
imagesets/generic-worker-win2012r2-staging/bootstrap.ps1
imagesets/generic-worker-win2012r2/bootstrap.ps1
imagesets/generic-worker-win2016/bootstrap.ps1

Work in progress to build windows images that run worker-runner.

Bug 1558532 - build windows images with worker-runner

---

imagesets/generic-worker-ubuntu-18-04-podman/bootstrap.sh
imagesets/generic-worker-ubuntu-18-04-staging/bootstrap.sh
imagesets/generic-worker-ubuntu-18-04/bootstrap.sh

(I haven't built these yet)
This will allow us to remove
https://github.com/taskcluster/taskcluster/blob/4f935ea671b1255f0f2598406e8fdeb656c3b75e/.taskcluster.yml#L334

Bug 1606948 -  install python venv tools in g-w ubuntu images

---

config/imagesets.yml

This version includes the new hostShmMemory device.

Upgrade google images with latest docker-worker

---

config/projects/relman.yml

See https://bugzilla.mozilla.org/show_bug.cgi?id=1609276.

Change bugbug bucket name to match what was used in the end

---

config/imagesets.yml

replaces an image we deleted a cleanup operation 😬

add new docker-worker-gcp-community image

---

config/grants.yml
config/projects/telemetry.yml

Just enough to experiment with creating some adhoc tasks for
now.

Add a preliminary configuration for telemetry

---

config/projects/rtems.yml

Add RTEMS project

---

config/grants.yml

Bug 1607935 - grant worker-pool secrets scopes to worker pools

---

config/projects/webrender.yml

Bug 1619284 - Remove obsolete secret token

---

config/projects/fuzzing.yml

Also move some secret scopes to master branch only, where they are only needed for CD not CI.

Add scopes to run tc-admin apply for proj-fuzzing

---

config/imagesets.yml

This image ships with the new certificate

Update docker-worker image

---

config/imagesets.yml

This has the new certificate and fixes boot logging time.

Deploy new docker-worker image

---

config/projects/taskcluster.yml

I missed this in my previous PR.

include queue:scheduler-id:test-scheduler for g-w tests, too

---

config/projects/bergamot.yml

Add project Bergamot

---

config/projects/taskcluster.yml

(already applied; see https://bugzilla.mozilla.org/show_bug.cgi?id=1622943)

Bug 1622943 - shrink reregistrationTimeout to 30 days

---

config/grants.yml

See [bug 1623035](https://bugzil.la/1623035) for context. Thanks!

Bug 1623035 - add missing scopes to login-identity:* parameterised role

---

config/projects/bergamot.yml

I've added grants required of [decision task](https://github.com/mozilla/marian-dev/blob/master/.taskcluster.yml)

Added grants required of decision task

---

config/projects/taskcluster.yml

This adds matrix scopes to the tc projects so that we can test it out in community

Add matrix scopes for tc project

---

config/imagesets.yml
config/projects/taskcluster.yml

Thanks to @djmitche for the instructions on building these images.

Deploy docker-worker 30.0.2

---

setup.py

upgrade tc-admin to 2.5.1

---

config/imagesets.yml
config/projects/taskcluster.yml

Seems to be working in testing..
https://community-tc.services.mozilla.com/tasks/QrjKgfgmSBKWxJHghUZcjw

upgrade docker-worker to 30.1.1

---

config/imagesets.yml

This updates the deepspeech Windows workers to use the new images I created today.

New EC2 machine images for deepspeech Windows workers

---

config/projects/deepspeech.yml

Add -beta worker types and instances to be able to test changes cleanly before updating the main workers.

Add macos-heavy-b and macos-light-b workers

---

imagesets/deepspeech-win2012r2-b/bootstrap.ps1
imagesets/deepspeech-win2012r2-gpu/bootstrap.ps1

@lissyx Who should I ping for a review?

Change UWP requirements to visualstudio2019buildtools

---

config/projects/taskcluster.yml

See https://github.com/taskcluster/taskcluster/issues/3276

copy perms from tc monorepo master to main

---

.taskcluster.yml

switch to main branch

---

config/projects/taskcluster.yml

This is required for the new test in taskcluster/taskcluster#3326

Add per-worker device/privileged scopes for docker-worker tests.

---

config/projects/taskcluster.yml

c.f. https://github.com/taskcluster/monopacker/pull/82

remove monopacker secrets

---

config/projects/fuzzing.yml

Fixes incorrect create-task scoping for bugmon-monitor.

Add create-task scope for bugmon-monitor

---

config/projects/fuzzing.yml

Adds missing scopes for fuzzing/bugmon project.

Add missing scopes for fuzzing/bugmon

---

config/grants.yml

I'm not sure with `to: *`. Please advise on the proper way to grant to everybody.

Add anonymous role

---

config/imagesets.yml
generate/workers.py

If there's a better way to go about disabling devices in aws only, let me know! This feels like a hack.

New images oct 30 2020

---

config/imagesets.yml

This deploys taskcluster/taskcluster#3900

use docker-worker 38.0.5

---

config/projects/taskcluster.yml

Refs taskcluster/taskcluster#3719

add a taskcluster-object secret, too

---

config/projects/mwz.yml

Add an mwz project to support experimentation

---

config/projects/taskcluster.yml

This is needed for taskcluster/taskcluster#4039.
Thanks!

Object Service CI AWS secrets in password store

---

config/projects/misc.yml

Codetribute needs to migrate off Travis-CI.

add access for codetribute

---

config/projects/fuzzing.yml

This should be the rest of the live changes. The role changes are intended to simplify things a bit by making some grants common.

Add more unapplied changes for fuzzing.

---

config/grants.yml

For taskcluster/taskcluster#4262.

add queue:create-task:project:none to Role=anonymous

---

config/projects/taskcluster.yml

Refs taskcluster/taskcluster#4779.

remove use of codecov.io

---

config/projects/misc.yml
config/projects/mwz.yml
config/projects/rtems.yml
imagesets/README.md
imagesets/docker/Dockerfile
imagesets/docker/TAG
imagesets/docker/signin-aws
setup.py

Dustin offboarding

---

config/projects/fuzzing.yml

Adds a hook for running the bugmon image weekly with the `--force-confirm` flag.

[fuzzing] Add hook for bugmon forced confirmation

---

config/projects/fuzzing.yml

This hook is already running on community-tc.

[fuzzing] Add hook to automatically update gridl grammar

---

imagesets/docker-worker/bootstrap.sh
imagesets/docker/Dockerfile
imagesets/generic-worker-ubuntu-18-04-podman/bootstrap.sh
imagesets/generic-worker-ubuntu-18-04-staging/bootstrap.sh
imagesets/generic-worker-ubuntu-18-04/bootstrap.sh
imagesets/imageset-under-docker.sh
imagesets/imageset.sh
imagesets/signin-aws.sh
misc/aws-worker-vpc-setup.sh

The shell scripts were quite inconsistently formatted - we could add this as a precommit lint or something - what do you think?
I've not used `shfmt` before, but it seems pretty good, and fast.

Format shell scripts

---

imagesets/imageset.sh
imagesets/signin-aws.sh

This should fix the problem @matt-boris was having, I hope!

fixes for imageset

---

imagesets/imageset.sh

The `imageset.sh` script builds machine images (expensive, time-consuming) and then updates password store with credentials to connect to new machine images. However, if there is a problem with the password store / gpg setup of the user running `imageset.sh`, they will only discover this after the new machine images have been built.
I added a pre-check that writing secrets to the password store works, before beginning the long process of generating machine images, to reduce chance of failure once the image building process has started.
At the same time, I modified the log routine to clear to end-of-line on line return, so that the background colour extends to the full terminal width on line returns (aesthetic improvement).
I also moved all checks to before the 'Starting!' log line and …

Fixups imageset

---

imagesets/imageset.sh

Looks like this isn't needed...

Updated gcloud command based on latest cli

---

imagesets/generic-worker-win2012r2/bootstrap.ps1

Soon we should upgrade to a newer version, but this should at least fix some of the issues with the current installation script.

Fix Windows Server 2012R2 installation steps

---

imagesets/generic-worker-win2012r2/bootstrap.ps1
imagesets/generic-worker-win2016/bootstrap.ps1
imagesets/imageset.sh

I ran a diff between the windows 2016 machine setup and the windows server 2012 r2 setup, and these are the patches I think we should make to align them.

Win2016 fixes

---

config/projects/fuzzing.yml

Runs a task weekly to determine if pref dependencies have been resolved.

Add hook for running prefpicker-monitor weekly

---

config/projects/fuzzing.yml

Reduce frequency of gr-css hook to once a week.

Reduce frequency of fuzzing's gr-css hook

---

config/projects/fuzzing.yml
generate/workers.py

CC @pyoor
Enable video/audio loopback on AWS again.

Fuzzing fixes

---

config/imagesets.yml

Awaiting @pyoor confirmation of successful tasks using new drivers now available on AWS images. Leaving in draft for now.

feat(images): audio/video enabled on aws images

---

config/projects/taskcluster.yml

revert temporary roles

---

config/projects/bugbug.yml

This looks like a copy-paste from generic worker config, which doesn't make much sense here.

Removed unused genericWorker config

---

config/projects/taskcluster.yml

To align with existing envs: https://github.com/mozilla-services/cloudops-infra/pull/4571

Updated smoketest client name

---

imagesets/generic-worker-ubuntu-22-04-staging/bootstrap.sh
imagesets/generic-worker-ubuntu-22-04/bootstrap.sh

Will rebuild images after this is merged 👍🏻

Add docker back to ubuntu 22.04 images

---

config/imagesets.yml

These should be the final images built for docker worker.

Upgrade docker worker image to v46.1.0

---

config/imagesets.yml
config/projects/fuzzing.yml
imagesets/generic-worker-win2016-amd/aws_base_instance_type
imagesets/generic-worker-win2016-amd/aws_filters
imagesets/generic-worker-win2016-amd/aws_instance_profile
imagesets/generic-worker-win2016-amd/aws_owners
imagesets/generic-worker-win2016-amd/bootstrap.ps1

Sorry about this @jschwartzentruber @pyoor !
This should restore your previous proj-fuzzing/grizzly-reduce-worker-windows worker pool machine image.

Restore proj-fuzzing/grizzly-reduce-worker-windows

---

config/projects/taskcluster.yml

Allow proj-taskcluster/gw-ubuntu-22-04 in taskcluster CI (for d2g work)

---

CODE_OF_CONDUCT.md
CONTRIBUTING.md

Spotted they were different to our other repos... This just aligns them.

Clean up contribution guidelines

---

imagesets/generic-worker-ubuntu-22-04-staging/bootstrap.sh
imagesets/generic-worker-ubuntu-22-04/bootstrap.sh
imagesets/generic-worker-win2022/bootstrap.ps1
imagesets/relman-win2012r2/bootstrap.ps1

I'll build new images once this lands.

Bump tc version to v48.0.0

---

imagesets/generic-worker-ubuntu-22-04-staging/bootstrap.sh
imagesets/generic-worker-ubuntu-22-04/bootstrap.sh
imagesets/generic-worker-win2022/bootstrap.ps1
imagesets/relman-win2012r2/bootstrap.ps1

I'll rebuild images once this new release has finished publishing.

chore: bump tc to v48.2.0

---

config/projects/fuzzing.yml

Sorry @matt-boris , I didn't notice this in #570 until it was applied.

Fix typo in fuzzing role.

---

imagesets/generic-worker-ubuntu-22-04-staging/bootstrap.sh
imagesets/generic-worker-ubuntu-22-04/bootstrap.sh
imagesets/generic-worker-win2022/bootstrap.ps1
imagesets/relman-win2012r2/bootstrap.ps1

https://taskcluster.github.io/changelog-viewer/#version=v49.2.0

chore: bump to tc v49.2.0

---

config/projects/taskcluster.yml

So we can play around with it....

Enable interactive feature on proj-taskcluster/gw-ubuntu-22-04 worker pool

---

imagesets/generic-worker-ubuntu-22-04/bootstrap.sh
imagesets/generic-worker-win2022/bootstrap.ps1
imagesets/relman-win2012r2/bootstrap.ps1

https://taskcluster.github.io/changelog-viewer/#releaseFrom=v50.0.0&releaseTo=v51.0.0

chore: bump tc to v51.0.0

---

config/projects/taskcluster.yml

Changes for https://github.com/taskcluster/taskcluster/pull/6331.

Update generic-worker/taskcluster-ci client to have the loopback-video scope

---

imagesets/generic-worker-ubuntu-22-04/bootstrap.sh
imagesets/generic-worker-win2022/bootstrap.ps1

https://docs.taskcluster.net/docs/changelog?version=v53.1.0

chore: bump tc to v53.1.0

---

config/projects/taskcluster.yml

This PR is safe to land and apply once https://github.com/taskcluster/taskcluster/pull/6342 is merged 👍🏻

chore: remove tc dw worker pools

---

imagesets/generic-worker-ubuntu-22-04/bootstrap.sh
imagesets/generic-worker-win2022/bootstrap.ps1

https://docs.taskcluster.net/docs/changelog?version=v53.2.1

chore: bump tc to v53.2.1

---

config/projects/taskcluster.yml

Reverts mozilla/community-tc-config#604
https://github.com/mozilla/community-tc-config/pull/604#issuecomment-1609659655

Revert "chore: remove tc dw worker pools"

---

imagesets/generic-worker-freebsd/bootstrap.sh
imagesets/generic-worker-ubuntu-22-04/bootstrap.sh
imagesets/generic-worker-win2022/bootstrap.ps1

New changes found here https://docs.taskcluster.net/docs/changelog?from=v54.0.0&to=v54.3.0

chore: bump to tc v54.3.0

---

config/projects/taskcluster.yml

Fixes https://github.com/taskcluster/taskcluster/issues/5968.
Fixes https://github.com/mozilla/community-tc-config/issues/623.

chore: migrate `proj-taskcluster/ci` to gw

---

config/projects/releng.yml

chore: migrate `proj-releng` to gw

---

config/projects/firefoxreality.yml

chore: migrate proj-firefoxreality to gw

---

config/projects/relman.yml

chore: migrate `proj-relman` to gw

---

config/projects/bors-ng.yml

chore: migrate `proj-bors-ng` to gw

---

config/projects/webrender.yml

chore: migrate `proj-webrender` to gw

---

config/projects/bugbug.yml

chore: migrate `proj-bugbug` to gw

---

config/imagesets.yml
imagesets/generic-worker-ubuntu-22-04-staging/bootstrap.sh
imagesets/generic-worker-ubuntu-22-04/bootstrap.sh

Fixes https://github.com/taskcluster/taskcluster/issues/6412.

fix: add virtual video device on gcp to fix generic worker

---

config/projects/bors-ng.yml
config/projects/bugbug.yml
config/projects/firefoxreality.yml
config/projects/git-cinnabar.yml
config/projects/releng.yml
config/projects/relman.yml
config/projects/webrender.yml

Fixes #651 
Fixes #653
Fixes #654
Fixes #655
Fixes #656
Fixes #657
Fixes #660

chore: migrate projects to gcp

---

imagesets/generic-worker-freebsd/bootstrap.sh
imagesets/generic-worker-ubuntu-22-04/bootstrap.sh
imagesets/generic-worker-win2022/bootstrap.ps1

https://github.com/taskcluster/taskcluster/blob/main/CHANGELOG.md#v5450

chore: bump tc to v54.5.0

---

imagesets/generic-worker-freebsd/bootstrap.sh
imagesets/generic-worker-ubuntu-22-04/bootstrap.sh
imagesets/generic-worker-win2022/bootstrap.ps1

https://docs.taskcluster.net/docs/changelog?version=v55.3.0

chore: bump to tc v55.3.0

---

config/projects/mozci.yml

chore: migrate `proj-mozci` to gw

---

.github/CODEOWNERS
config/imagesets.yml
config/projects/taskcluster.yml
imagesets/README.md
imagesets/generic-worker-win2016-amd/bootstrap.ps1
imagesets/imageset.sh
setup.py

Related to https://bugzilla.mozilla.org/show_bug.cgi?id=1857024.

chore: update community-tc-config links [skip ci]

---

config/projects/bugbug.yml

Added `queue:route:checks` to the bugbug project

---

imagesets/generic-worker-win2016-amd/bootstrap.ps1

The AMD driver required by Windows fuzzing workers is still not supported on Windows Server 2022, so refreshing Windows Server 2016 image, to realign with Windows Server 2022.
This also unblocks an issue where fuzzing jobs need to run as root to disable/uninstall Windows Defender, since this has now been removed from the base image, like it is on Windows Server 2022 machine images. This means those fuzzing tasks will no longer need to run as Administrator, which should help with an issue where some tasks seem to inadvertently shutdown the machine, which causes tasks to be resolved as exception/claim-expired. When not running as Administrator, they should (hopefully) not be able to shutdown the machine.

Update Windows Server 2016 (amd64) image for fuzzing workers

---

config/imagesets.yml
imagesets/generic-worker-ubuntu-22-04-staging/bootstrap.sh
imagesets/generic-worker-ubuntu-22-04/bootstrap.sh

In #700 we got linux/wayland stuff working on staging worker pool.
This PR is an attempt to reduce the changes to the minimum set required, as I suspect not all of the steps are required.

Reduce wayland fixes to minimum required set

---

config/projects/taskcluster.yml

See taskcluster/taskcluster#6789 for details.

New Generic Worker CI scope for taskcluster/taskcluster#6789

---

config/imagesets.yml
config/projects/taskcluster.yml
imagesets/generic-worker-ubuntu-22-04-staging/bootstrap.sh
imagesets/generic-worker-ubuntu-22-04/bootstrap.sh

Will initially deploy to staging to test that it is working as expected.

Create unix group snap_sudo on ubuntu workers for running snap commands in tasks

---

config/imagesets.yml
config/projects/fuzzing.yml
config/projects/taskcluster.yml
imagesets/generic-worker-ubuntu-22-04-staging/bootstrap.sh
imagesets/generic-worker-ubuntu-22-04-staging/gcp_filters
imagesets/generic-worker-ubuntu-22-04/bootstrap.sh

Attempting to add support for snd-aloop on our ubuntu staging pools (in both aws/ec2 and gcp/gce).
Fixes #616
CC @pyoor @matt-boris @jschwartzentruber

Enable snd-aloop on ubuntu staging pools

---

config/projects/misc.yml
imagesets/generic-worker-ubuntu-22-04-staging/bootstrap.sh
imagesets/generic-worker-ubuntu-22-04/bootstrap.sh

See:
* https://github.com/taskcluster/taskcluster/pull/7060
* https://help.ubuntu.com/community/KVM/Installation

Install kvm packages on generic-worker-ubuntu-22-04(-staging)

---

imagesets/imageset.sh

Shorter generated azure entity names

---

config/projects/mozci.yml

Incident which required longer interval has been resolved.

Switch back to 10 minute interval for mozCI decision task

---

imagesets/generic-worker-win2016-amd/bootstrap.ps1
imagesets/generic-worker-win2022-staging/bootstrap.ps1
imagesets/generic-worker-win2022/bootstrap.ps1

Fix python installation on Windows

---

config/projects/fuzzing.yml

- remove unused ci-gw pool
- remove oversized input types (cc: @pyoor)
- increase maxruntime and add timeout retry on coverage-revision

Fuzzing config updates

---

config/imagesets.yml
imagesets/generic-worker-ubuntu-22-04-staging/bootstrap.sh
imagesets/imageset.sh

This is to test IMDSv2 support in Worker Runner before landing the code fixes.

Build Ubuntu staging worker pool from tc branch issue7076

---

imagesets/generic-worker-ubuntu-24-04-arm64/bootstrap.sh

fix broken link

---

imagesets/generic-worker-win2022/bootstrap.ps1

Use Get-PnpDevice with Vendor ID 0x10DE to detect presence of NVIDIA GPU on Windows

---

config/imagesets.yml
config/projects/fuzzing.yml

Use Ubuntu 24.04 in proj-fuzzing/bugmon-pernosco-staging, not Ubuntu 22.04

---

generate/workers.py

I noticed that a few of the new azure worker pool configs are using the same dict format as we use for aws and gcp. This was accidentally set to a list instead of a dict when I first created it. This change makes it consistent across the board so that it matches what our `config/projects/README.md` file says.
It just so happens that even though the generation code was written for a list input, it still works as expected when users were giving the dictionary type, so this PR should be a `no-op` as far as running `tc-admin diff`.

fix(azure): use consistent instance types dictionary in config

---

imagesets/generic-worker-ubuntu-24-04/bootstrap.sh

This merges the staging changes we had back into the main image.

Promote staging kernel parameter changes in Ubuntu 24.04

---

imagesets/generic-worker-ubuntu-24-04-staging/bootstrap.sh

install google cloud ops agent

---

config/projects/bors-ng.yml
config/projects/bugbug.yml
config/projects/fuzzing.yml
config/projects/git-cinnabar.yml
config/projects/misc.yml
config/projects/mozci.yml
config/projects/releng.yml
config/projects/relman.yml
config/projects/taskcluster.yml
config/projects/webrender.yml
config/projects/wpt.yml

This is a temporary workaround since everything broke in GCP 😬

Move everything from gcp to aws as workaround for broken worker pools

---

imagesets/generic-worker-ubuntu-24-04-staging/bootstrap.sh

Let's see if this magically fixes things.

Issue 796: try removing snd-aloop configuration in staging

---

imagesets/generic-worker-ubuntu-24-04-staging/bootstrap.sh

Add stuff back... who knows?

---

imagesets/generic-worker-ubuntu-24-04-staging/bootstrap.sh

This reverts commit 2c3578867bfc8121cce9ef013645520c8929f23c.

Revert "Add stuff back... who knows?"

---

imagesets/generic-worker-ubuntu-24-04-staging/bootstrap.sh
imagesets/generic-worker-ubuntu-24-04/bootstrap.sh

fix obsolete output type

---

imagesets/generic-worker-ubuntu-24-04/bootstrap.sh

This merges the staging changes to the production pools.

Issue 796: Fix Ubuntu 24.04 workers in GCP that were not starting up

---

config/imagesets.yml

Sort entries in imagesets.yml, set idle timeout everywhere and enable interactive feature by default.

Clean up imagesets.yml

---

imagesets/generic-worker-ubuntu-24-04-staging/bootstrap.sh

Taken from https://unix.stackexchange.com/a/126146.

fix(ubuntu): wait for networking on 24.04 staging

---

imagesets/generic-worker-ubuntu-24-04/bootstrap.sh

After a working test from https://github.com/taskcluster/community-tc-config/pull/811.

fix(ubuntu): wait for networking on 24.04

---

config/projects/taskcluster.yml

Decision task failed on merge to main https://community-tc.services.mozilla.com/tasks/RBflxBkkT5qCFToZ2D-89w

chore: need one more route for docker image builder

---

config/projects/fuzzing.yml

CC @jschwartzentruber @pyoor
As discussed today in the taskcluster fuzzing meeting...

proj-fuzzing/grizzly-reduce-worker-android -> generic-worker (was docker-worker)

---

imagesets/generic-worker-freebsd/bootstrap.sh
imagesets/generic-worker-ubuntu-24-04/bootstrap.sh
imagesets/generic-worker-win2022-staging/bootstrap.ps1
imagesets/generic-worker-win2022/bootstrap.ps1
imagesets/imageset.sh

Fixes https://github.com/taskcluster/community-tc-config/issues/607.

fix: don't delete old resources to make rollbacks easier

---

config/projects/fuzzing.yml

Adding arm64 support to [orion](https://github.com/MozillaSecurity/orion/)

Add arm64 ubuntu worker for fuzzing

---

generate/workers.py

Fix true -> True

---

imagesets/imageset.sh

Sometimes an `az` command fails silently. When it passes, we don't want to show the stdout and stderr, but if it fails we do. Previously we were just sending output to /dev/null but with this PR, we will write it to a temporary file, and then only log it if the command fails.

Log output from az commands if they fail, but not if they pass

---

imagesets/imageset.sh

Hopefully this should fix the quota issues we have been hitting...

Delete old resource groups in azure to avoid hitting quotas

---

imagesets/generic-worker-ubuntu-24-04-staging/bootstrap.sh
imagesets/generic-worker-win2022-staging/bootstrap.ps1
imagesets/generic-worker-win2022/bootstrap.ps1

Fixes https://github.com/taskcluster/community-tc-config/issues/838.

build windows staging from source

---

config/imagesets.yml
config/projects/taskcluster.yml
imagesets/generic-worker-ubuntu-24-04-staging/bootstrap.sh
imagesets/generic-worker-win11-24h2-staging/azure_base_instance_type
imagesets/generic-worker-win11-24h2-staging/azure_image
imagesets/generic-worker-win11-24h2-staging/bootstrap.ps1
imagesets/generic-worker-win11-24h2-staging/sysprep.ps1
imagesets/generic-worker-win2022-staging/bootstrap.ps1
imagesets/generic-worker-win2022/bootstrap.ps1

Creating a dedicated pool for testing Windows 11 24H2.

Test Generic Worker on Windows 11 24H2

---

imagesets/generic-worker-win11-24h2-staging/bootstrap.ps1
imagesets/generic-worker-win2022-staging/bootstrap.ps1

This ended up being quite a few cleanups in one. I hope I didn't bite off too much.
I propose when we deploy this, we write a script that checks all of the installation steps, and then we run it as a task on the staging pool. If we can get it to work, we can make it part of the deployment steps, so we are sure that all the parts continue to work and don't silently fail, or succeed but not actually do what we intend them to do...

Big Windows staging bootstrap cleanup

---

imagesets/README.md

Update imageset.sh docs

---

imagesets/imageset.sh

See https://github.com/petemoore/myscrapbook/blob/d47a141c6f3453dbe569ee5ce79a5a77208929de/build-gw-images.sh#L39-L42
This takes a lot of time during image building due to locking. This should save some time.

Performance optimisation - only blow away old resource groups in build-gw-images.sh

---

imagesets/generic-worker-win2022-staging/bootstrap.ps1

Moar Windows staging fixes

---

imagesets/generic-worker-win2022-staging/bootstrap.ps1

Windows staging fixes

---

imagesets/README.md
imagesets/imageset.sh

`imageset.sh all`, to build and deploy all image sets in parallel

---

imagesets/generic-worker-win2022/bootstrap.ps1

This just patches prod with what was working in staging.

Deploy staging Windows changes to production

---

imagesets/generic-worker-ubuntu-24-04-staging/bootstrap.sh
imagesets/generic-worker-win2022-staging/bootstrap.ps1

This deploys taskcluster/taskcluster#7324 to `proj-taskcluster/gw-ubuntu-staging-google` and `proj-taskcluster/gw-ubuntu-staging-aws`.

Test taskcluster/taskcluster#7324 on ubuntu staging

---

config/projects/fuzzing.yml

Add hook and worker for nss-corpus-update

---

config/projects/taskcluster.yml

Needed for https://github.com/taskcluster/taskcluster/pull/7342.

chore: add generic worker cache to monorepo

---

config/imagesets.yml
imagesets/generic-worker-freebsd/bootstrap.sh
imagesets/generic-worker-ubuntu-24-04/bootstrap.sh
imagesets/generic-worker-win2022/bootstrap.ps1

Since 73.0.0 seems to have some problems.

Roll back 73.0.0

---

imagesets/generic-worker-ubuntu-24-04-staging/bootstrap.sh
imagesets/generic-worker-ubuntu-24-04/bootstrap.sh

As suggested from https://github.com/mozilla-platform-ops/worker-images/pull/89.

chore: don't install gnome-initial-setup

---

config/imagesets.yml
imagesets/generic-worker-freebsd/bootstrap.sh
imagesets/generic-worker-ubuntu-24-04/bootstrap.sh
imagesets/generic-worker-win2022/bootstrap.ps1

Rolling back v75.0.0 to v74.0.0 due to https://github.com/taskcluster/taskcluster/issues/7404.

chore: revert to TC v74.0.0

---

generate/workers.py

Followup to https://github.com/taskcluster/community-tc-config/pull/891. We'll get 400's if we try to update worker pool configs with this additional field.

fix: only generate `workerManager` config for azure pools

---

config/imagesets.yml

Reverts 24cdfca8aef6f6b5205e722c5a1ee3361fcf83f1  and  5e3937608c18637f0765f347c9ce7516845d7acf

Reverts last two image upgrades

---

config/imagesets.yml

Reverts taskcluster/community-tc-config#897

Revert "Reverts last two image upgrades"

---

imagesets/imageset.sh

This will greatly reduce our time spent rebuilding production images.

chore: don't build staging images by default

---

imagesets/generic-worker-ubuntu-24-04-arm64/gcp_filters
imagesets/generic-worker-ubuntu-24-04/bootstrap.sh
imagesets/generic-worker-ubuntu-24-04/gcp_filters

Also pin ubuntu base image, as we've done for staging.
Copies https://github.com/taskcluster/community-tc-config/commit/d68ebed26179418900f4b92016312786f89d102b.

fix: rearrange package installs to fix resolution of linux module package

---

config/imagesets.yml
imagesets/imageset.sh

chore: only build staging images in one region

---

generate/workers.py

Calculates the launch config ID similar to how it's done in the DB for worker manager https://github.com/taskcluster/taskcluster/blob/3619a4113f056d13f1081d70eb30305da6018a5d/db/versions/0105-migration.sql#L25-L37 (aside from the fact that we're using `sha256` in this implementation).
Also moves `capacityPerInstance` to `workerManager` block in config, as previous config is deprecated.
Related to changes from https://github.com/taskcluster/taskcluster/pull/7266.

fix: adjust worker pool generation based on new launch config changes

---

imagesets/generic-worker-ubuntu-24-04/bootstrap.sh

_Should_ fix https://github.com/taskcluster/taskcluster/issues/7582.
This aligns with the recent staging changes that are tested in the comment below https://github.com/taskcluster/community-tc-config/commit/d2dc92f9da774b9686d6d5dead092091d5fb8fa4.

fix(linux): also install most recent kernel modules

---

imagesets/imageset.sh

Fixes https://github.com/taskcluster/community-tc-config/issues/933.

fix(azure): remove security type to fix VM creation

---

imagesets/imageset.sh
misc/update-azure-vm-sizes.sh

fix(azure): use `az vm list-skus`

---

imagesets/imageset.sh

To update these workers https://community-tc.services.mozilla.com/provisioners/proj-taskcluster/worker-types/gw-ci-macos?sortBy=Last%20Active&sortDirection=desc.

chore: update parallel imageset to deploy to new macs

---

setup.py

Hope this will fix
```
Traceback (most recent call last):
File "/Users/pmoore/tc-admin/tc-admin-venv/bin/tc-admin", line 7, in <module>
sys.exit(boot())
^^^^^^
File "/Users/pmoore/tc-admin/tc-admin-venv/lib/python3.12/site-packages/tcadmin/boot.py", line 65, in boot
main(appconfig)
File "/Users/pmoore/tc-admin/tc-admin-venv/lib/python3.12/site-packages/tcadmin/main.py", line 140, in main
cmd()
File "/Users/pmoore/tc-admin/tc-admin-venv/lib/python3.12/site-packages/click/core.py", line 1442, in __call__
return self.main(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/Users/pmoore/tc-admin/tc-admin-venv/lib/python3.12/site-packages/click/core.py", line 1363, in main
rv = self.invoke(ctx)
^^^^^^^^^^^^^^^^
File "/Users/pmoore/tc-admin/tc-admin-venv/lib/python3.12/site-packages/click/core.py …
```

Update tc-admin from 4.0.1 to 5.0.3

---

config/projects/taskcluster.yml

Needed for https://github.com/taskcluster/taskcluster/pull/7935

Add scopes to taskcluster repo for running docker in proj-taskcluster/gw-ubuntu-24-04-gui

---

config/projects/fuzzing.yml

cc @jschwartzentruber @moz-mdauer

[fuzzing] Grant mdauer access to private fuzzing logs
