generate/repo_access.py
```
vagrant@vagrant:community-tc-config  (docker-worker-scopes)$ TASKCLUSTER_ROOT_URL=https://community-tc.services.mozilla.com tc-admin diff --grep docker-worker
--- current
+++ generated
@@ -3,9 +3,22 @@
- Role=repo:.*
- Role=project-admin:.*
- Role=github-org-admin:.*
- Role=github-team:.*
- Role=login-identity:.*
- WorkerPool=proj-.*
resources:
+  Role=repo:github.com/taskcluster/docker-worker:
+    roleId: repo:github.com/taskcluster/docker-worker
+    description:
+      *DO NOT EDIT* - This resource is configured automatically.
+
+    scopes:
+      - docker-worker:cache:docker-worker-garbage-*
+      - docker-worker:capability:device:loopbackAudio
+      - docker-worker:capability:device:loopbackVideo
+      - docker-worker:capability:privileged
+      - …
```
=> Bug 1587555: Add scopes necessary for docker-worker CI

config/projects.yml
this is pretty broad, so it's up for debate if this is the right approach.
this essentially allows any project in the mozilla organization access to this worker-pool
=> add mozilla project

config/projects.yml, generate/projects.py
This is useful for generating standalone worker credentials, for example.
=> Add support for configuring per-project clients

misc/aws-worker-vpc-setup.sh
Without this, the hosts can't communicate with the outside world, which fills them with sadness and prevents them from doing their jobs.
=> Bug 1592025 - assign public IPs to all hosts

config/projects.yml
This adds:
* a project with glandium as admin
* a docker-worker workerpool named "ci"
* a win2012r2 workerpool named "win2012r2"
* clients for some workers that run in Travis-CI (!!)
* role configuration to allow tags, branches, and releases to have index routes and access to the code-coverage secret
https://bugzilla.mozilla.org/show_bug.cgi?id=1574663
=> Bug 1574663 - Add a git-cinnabar project with some workers

config/grants.yml, generate/__init__.py, generate/login_identity.py
The `login-identity:*` role was overlooked when moving other
parameterized roles into `grants.yml` -- oops!
This also adds `scheduler-id:-` for all logged-in users.  This
schedulerId is the default, so is used for tasks created with "task
creator".  Adding it doesn't hurt.
=> Move login-identity:* into grants, add scheduler-id:-

config/projects.yml
Note that this does not add the win2012r2 worker for FirefoxRealityPC -- we can do that in a follow-up.
=> Bug 1574661 - add firefoxreality project

config/projects.yml
This is much simpler than what is in the old deployment right now
because we can't deploy across deployments
=> Set up project relman stuff in its entirety

config/projects.yml
This project just has its own (dedicated) docker-worker worker pool.  As configured, this will run in GCP, but the effect should be pretty similar to the existing AWS worker type.
We can add to `adminRoles` as necessary -- if there's individual GitHub users who should have access, or GitHub teams, or all org admins of the wpt org.
=> Bug 1574668 - add a 'wpt' project

config/projects.yml
This was "accidentally" granted to team_moco in the old deployment (by virtue of granting `queue:get-artifact:private/*`).  I don't want to grant it too widely in the community deployment -- I'd rather wait until we have a better interactive story to support it at all.
=> Bug 1593165 - grant glandium access d-w interactive sessions

config/grants.yml
This can be useful after changing the pool’s configuration
=> Grant `worker-manager:remove-worker:proj-<..>/*` to project admins

config/grants.yml
Rather than `*`, this allows just the existing providers.  That way, if we later add a project-specific provider, all admins won't have access to it.
=> Allow admins use of all providers

config/projects.yml
Theeherder scopes were previously granted through https://tools.taskcluster.net/auth/roles/project%3Aservo%3Agrants%2Ftreeherder. I couldn’t find what role grants IRC scopes on taskcluster.net, though.
=> Grant scopes for IRC and Treeherder routes to Servo admins

config/projects.yml
...to support making hooks that use this schedulerId
=> Grant `queue:scheduler-id:taskcluster-github` to servo

config/projects.yml
The underscores in the project name are incompatible with the GCP
provider.  This project only runs simple lint/CI, so misc is sufficient,
rather than renaming the project to `tcymlvalidator` or the like.
=> Move taskcluster_yml_validator to the misc project

config/projects.yml, generate/projects.py
```diff
(sandbox) dustin@lamport ~/p/community-tc-config [cinnabar-repos] $ tc-admin diff --grep cinnabar                                                                                                                                                                                                                                                                           
--- current                                                                                                                                                                                                                                                                                                                                                                 
+++ generated
@@ -17,16 +17,24 @@ …
```
=> Add repo admin for git-cinnabar

config/projects.yml
- the redo project is a releng project, but there are others, i.e. maven-lambda
- this lets us share the worker-pool across those projects
=> replace redo project with releng project

config/projects.yml
Because of https://bugzilla.mozilla.org/show_bug.cgi?id=1593792 and also 
`<SimonSapin> There are also errors like: Invalid value for field 'resource.machineType': 'zones/us-east4-a/machineTypes/n2-highcpu-16'. Machine type with name 'n2-highcpu-16' does not exist in zone 'us-east4-a'.`
=> use n1- instances for servo

config/projects.yml
https://community-tc.services.mozilla.com/tasks/UxQR1tHSRN6imKedMGQGsQ/ failed twice in a row with an error message that *might* indicate low disk space.
=> Request mork disk space for Servo workers

config/projects.yml
See [bug 1575648](https://bugzil.la/1575648) for context.
I'm not entirely sure I've captured everything here, but I think this should get us most of the way.
* https://github.com/servo/webrender/blob/master/.taskcluster.yml
* [github.com/servo/webrender](https://github.com/servo/webrender)
* [github.com/staktrace/webrender](https://github.com/staktrace/webrender)
* aws-provisioner-v1/github-worker
* localprovisioner/webrender-ci-osx
* project/webrender-ci/macos
* assume:worker-type:localprovisioner/webrender-ci-osx
* mozillians-group:webrender-ci
* assume:project-admin:webrender-ci
* project:webrender-ci:grants/github-repos
* assume:github-admin:servo/webrender
* project:webrender-ci:grants/workers
* queue:quarantine-worker:localprovisioner/webrender-ci-osx/*
* …
=> Bug 1575648 - migrate webrender to taskcluster community deployment

config/projects.yml
changes:
- includes lz4 per https://github.com/taskcluster/monopacker/pull/27
The idea is to test the taskcluster projects with this image, if things seem OK we'll replace the default.
=> update taskcluster project docker_worker_gcp image

config/grants.yml
It’s not terribly important. Project admin is what I’ve been granting to laptop / CLI clients.
=> Grant task management to Servo through project admin role instead of github team role

config/projects.yml
This does not include any `runtime` secrets (other than bugbug) which will only exist in the firefox-ci deployment. We have decided to run bugbug entirely in the community cluster iiuc.
=> Add relman secrets

config/projects.yml
=> deepspeech: add ssh-key secrets, allow project-admins to get

config/grants.yml, config/projects.yml
=> Admins get access to private/docker-worker artifacts

config/projects.yml
This is causing the hook to fail.  I've already deployed.
=> add scheduler-id '-' to release-metrics hook

config/projects.yml
The task seems to need slightly longer than on taskcluster.net
=> Bump maxruntime for jcristau-fx-release-metrics

config/projects.yml
This is to support bugbug deploying its own hooks
=> Make relman externally managed

config/projects.yml
Add `queue:scheduler-id:taskcluster-github` grants to `repo:github.com/web-platform-tests/wpt:*` to allow decision task to schedule tasks.
=> Add queue:scheduler-id:taskcluster-github to wpt

config/projects.yml
The project is currently saturating the 40 worker pool and PRs are frequently waiting on Taskcluster c.f. https://github.com/web-platform-tests/wpt/issues/20256
=> Increase wpt maxCapacity to 80

config/projects.yml
This should have no effect -- I've changed "queue:claim-work:<workerPoolId>" to "[assume:worker-pool:<workerPoolId>](https://community-tc.services.mozilla.com/auth/roles/worker-pool%3A*)" which implies the former scope.  Similarly for "[assume:worker-id:<workerGroup>/<workerId>](https://community-tc.services.mozilla.com/auth/roles/worker-id%3A*)".
/cc @jgraham @glandium
=> Use assume:worker-{pool,id} for worker clients

config/grants.yml
Then when we make this the default value in task-creator, it will "just work"
=> Bug 1596171 - give everyone schedulerId taskcluster-ui

config/projects.yml
We’ve added a number of Linux tasks to CI recently, and have occasionally reached the previous maximum since.
=> Raise maxCapacity for Servo’s worker pools

README.md, config/projects.yml, generate/__init__.py, generate/grants.py, generate/projects.py, generate/secret_values.py, generate/workers.py
I sort of threw this together.  If this is the wrong approach, let me know.
For the most part (except for our azure secret), this leaves existing secrets externally managed.  That's probably best for most projects other than taskcluster, anyway.
What this will really help with is worker-pool secrets -- those are now managed automatically.
=> Bug 1583990 - manage secrets with values from passwordstore

config/projects.yml
I think this makes sense since I'm adding secrets and fuzzing team may be doing more than CI in the near future.
=> Move MozillaSecurity repos to a separate project: fuzzing

config/projects.yml
I've decided to split this up into several bite size parts that can be landed independently.
This first part adds generic-worker CI roles and clients.
The next part is a little more disruptive, but this part shouldn't have any surprises.
Thanks!
=> Bug 1587554 - part 1: add generic-worker CI roles and clients

config/imagesets.yml, config/projects.yml, generate/imagesets.py, generate/projects.py, generate/workers.py
The aim of this second PR is to restructure the organisation of the code and configs a little to enable additional metadata to be associated to machine images, and provide a slightly more generic means for worker config to be associated to worker pools.
=> Bug1587554 part 2: restructure code/config to use image sets

config/projects.yml
Store generic-worker integration test credentials in secret `project/taskcluster/testing/generic-worker/ci-creds`.
=> Bug1587554 part 3: store generic-worker integration test credentials

config/projects.yml
This adds clients for my raspberry pi and Windows 10 on ARM (laptop) generic-worker workers that are used in generic-worker CI. Currently we don't have a managed worker pool, so I just have a single worker of each time on my own hardware, to help pick up issues early for Windows/Linux on ARM.
=> Bug 1587554 part 4: add clients for manually configured workers

config/projects.yml
This is a stop gap for generic-worker CI until we have an azure provider.
=> Add client for manually configured proj-taskcluster/gw-ci-windows10-amd64

config/imagesets.yml, generate/projects.py, generate/workers.py
This adds support for enabling `generic-worker` or `docker-worker` specific scopes, and cloud-specific scopes. This use case for this was wanting to give `auth:sentry:generic-worker` to all generic-worker workers.
=> Support worker-implementation specific scopes, shrink generic-worker configs, and configure deploymentId

config/projects.yml
I'm adding [integration tests to the code-review project](https://github.com/mozilla/code-review/issues/297) and need a few more scopes:
- the github worker need to be able to create & update a hook on the community instance
- the hook need to send emails & read a secret
Thanks !
=> Add scopes for code-review integration tests hooks.

config/grants.yml, config/projects.yml
These clients already exist so I just imported them into this config. Let me know if you'd rather manually configure them, @marco-c (I think maybe client support didn't exist here when we first set up relman).
This also gives all of the "admin types" broad notify permissions.
=> [Bug 1601810] Allow relman to notify

config/imagesets.yml
I deployed this using the `imageset.sh` script from #148.
Currently the `proj-taskcluster/gw-ci-windows2012r2-amd64` production pool runs in GCP and is on [version 16.1.0](https://github.com/taskcluster/community-history/blob/ab409f11f66d61e2d3335dc188b64af45d00f339/WorkerVersions/proj-taskcluster%E2%81%84gw-ci-windows2012r2-amd64) but this upgrade to [16.5.5](https://github.com/taskcluster/generic-worker#in-v1655-since-v1654) on staging will allow us to test it before rolling out to production.
=> Upgrade proj-taskcluster⁄gw-ci-windows2012r2-amd64-staging to generic-worker 16.5.5

config/imagesets.yml, imagesets/generic-worker-ubuntu-18-04-staging/bootstrap.sh, imagesets/generic-worker-win2012r2-staging/bootstrap.ps1
Rolling out [generic-worker 16.5.6](https://github.com/taskcluster/generic-worker/releases/v16.5.6) to staging image sets.
=> Roll out generic-worker 16.5.6 to Ubuntu/Windows staging image sets

config/projects.yml
So we can reuse the existing robustcheckout clones
=> Add cache for code-review integration tests hooks.

config/projects.yml
Since deploy keys can only be used on one github repo each, we will need a namespace instead.
=> Rename fuzzing deploy keys

config/projects.yml
Change admin to a manageable team instead of the Github org owner so we can separate these privileges.
=> Change fuzzing project admin.

config/projects.yml
```
The role hook-id:project-fuzzing/decision does not have sufficient scopes to create the task:
Client ID static/taskcluster/hooks does not have sufficient scopes and is missing the following scopes:
{
"AnyOf": [
{
"AllOf": [
"queue:scheduler-id:-",
{
"AnyOf": [
"queue:create-task:highest:proj-fuzzing/decision",
"queue:create-task:very-high:proj-fuzzing/decision",
"queue:create-task:high:proj-fuzzing/decision",
"queue:create-task:medium:proj-fuzzing/decision",
"queue:create-task:low:proj-fuzzing/decision",
"queue:create-task:very-low:proj-fuzzing/decision",
"queue:create-task:lowest:proj-fuzzing/decision"
]
}
]
},
{
"AnyOf": [
"queue:create-task:proj-fuzzing/decision",
{
"AllOf": [
"queue:define-task:proj-fuzzing/decision",
"queue:task-group-id:-/W-NdF07pSEascutMuX5hvw", …
```
=> Allow triggering the fuzzing decision task manually

config/projects.yml
Would `assume:hook-id:project-relman/bugbug*` work? Or do I have to specify each?
=> Add new hook scopes to bugbug deploy role

config/projects.yml
- On release (tag), the main hook is deployed;
- When the main hook ends, the other hooks can be deployed (as they depend on the result of the main hook; if the main hook doesn't run or fails, the other hooks should be kept in their previous version).
=> Allow main bugbug hook to modify other bugbug hooks

config/projects.yml
Blocks https://github.com/mozilla/code-coverage/pull/335
=> Allow mozilla/code-coverage to read release secret on tag push.

config/imagesets.yml
Without this, the machines stay running forever, wasting resources.
=> Bug 1606508 - shutdown g-w machines on idle

config/projects.yml
This adds the scope required by PR: https://github.com/taskcluster/docker-worker/pull/532 (disable seccomp)
I'm not sure if this needs to land before that PR or vice versa.
=> Add disable-seccomp scope to proj-taskcluster/ci for docker-worker

config/projects.yml
See [bug 1608828](https://bugzil.la/1608828) for context. Thanks!
=> Bug 1608828 - grant generic-worker CI rights to monorepo

config/projects.yml
This way we can create new caches easily.
=> Grant generic docker-worker:cache:bugbug-* to project:relman:bugbug/build

config/projects.yml
Bugzilla Bug: [1588083](https://bugzilla.mozilla.org/show_bug.cgi?id=1588083)
Small change per @tomprince's request in https://phabricator.services.mozilla.com/D58272#inline-366030
=> Bug 1588083 - use scheduler-id:smoketest for smoketests

config/projects.yml
This hook has been failing on missing scope `queue:create-task:medium:proj-fuzzing/decision` for some time.
=> Fix fuzzing hook scopes

config/imagesets.yml, config/projects/taskcluster.yml, generate/projects.py, generate/workers.py
This might be easiest to review commit-by-commit, as it was a bit of a refactor.
I only added one worker pool so far.  We can take that one to the finish line, then revisit for the others.
This *does* look forward to the day when we can provide config to static workers, at which time we can specify those in imagesets.
=> Bug 1607935 - support static workers

config/projects/fuzzing.yml
As discussed with @petemoore & @jschwartzentruber  yesterday, we are replacing the fuzzing decision  hook by tasks triggered by the Github repo https://github.com/MozillaSecurity/fuzzing-tc-config
=> Remove fuzzing decision hook

config/projects/taskcluster.yml
This will help reduce pending times during working hours while waiting for taskcluster monorepo generic-worker decision task to run.
=> Increase idle timeout of proj-taskcluster/windows2012r2-amd64-ci worker pool to 1h

config/projects/fuzzing.yml
Blocks https://github.com/MozillaSecurity/fuzzing-tc/pull/18
=> Allow github repo MozillaSecurity/fuzzing-tc to publish in index

config/projects/fuzzing.yml
This PR does several things:
1. Remove the useless `decision` worker pool, we only need `ci` to be static
2. Remove the privileged mode from `ci` worker pool, as the [docker image is now built with dind](https://github.com/MozillaSecurity/fuzzing-tc/issues/8)
3. As `tc-admin diff` now runs on every [MozillaSecurity/fuzzing-tc-config](https://github.com/MozillaSecurity/fuzzing-tc-config) pull request, we need to run `tc-admin apply` on every merge on master. So worker-manager scopes are requested for that branch.
=> Build fuzzing worker pools with Taskcluster CI/CD

config/gcp.yml, generate/workers.py
This is the same PR as #167 but for GCP.
It's needed by the fuzzing decision task - to be able to build workerpools on GCP
=> Move GCP constants in dedicated YAML file

config/projects/taskcluster.yml
Originally attempted in #199 I realised afterwards I updated the wrong worker pool!
This time I was more careful. ;-)
Also updating the Windows Server 2012 R2 CI worker pool for similar gain.
Thanks!
=> Increase idle timeout for generic-worker CI tasks

config/projects/fuzzing.yml
As hooks & worker pools are managed through https://github.com/MozillaSecurity/fuzzing-tc
=> Set fuzzing project as externally managed.

config/projects/taskcluster.yml
This scope ends with a `"`" character, so the `*` beforehand does not
match anything.  Thus this role would only work for a workerId of `*"`,
which we don't have.  So, the scope is unnecessary.
=> remove unnecessary, invalid scope

config/projects/taskcluster.yml
We seem to have some problems in gcp at the moment, and I think since long term we're not too concerned about having windows workers in gcp, let's just move to aws and save ourselves some troubleshooting.
See https://community-tc.services.mozilla.com/provisioners/proj-taskcluster/worker-types/windows2012r2-amd64-ci
=> Move taskcluster windows workers from gcp to aws

config/projects/servo.yml
I don’t know if an alias like `#servo:mozilla.org` works of if the full ID `!crXxRMedJXFPxKffWI:mozilla.org` is required so this adds both so I can try them.
Does the dot in `mozilla.org` need to be escaped?
CC https://bugzilla.mozilla.org/show_bug.cgi?id=1522154
=> Grant to Servo admins scope to notify their Matrix room

config/projects/taskcluster.yml
I noticed this was missing when I went to test denylisting matrix notifications.
=> Add denyist administration for TC team

config/projects/taskcluster.yml
Fixes failures like [this](https://community-tc.services.mozilla.com/tasks/XpiGh08eTAC-geB1NMzTEw/runs/0/logs/https%3A%2F%2Fcommunity-tc.services.mozilla.com%2Fapi%2Fqueue%2Fv1%2Ftask%2FXpiGh08eTAC-geB1NMzTEw%2Fruns%2F0%2Fartifacts%2Fpublic%2Flogs%2Flive.log)
=> Grant non-deprecated scopes to g-w CI

config/projects/cia.yml
Is it fine that I grant `secrets:get:project/cia/garbage/foo` to both the hook and the repo?
=> Grant scopes to CIA hook and repo

imagesets/deepspeech-win2012r2-gpu/bootstrap.ps1, imagesets/deepspeech-win2012r2/bootstrap.ps1, imagesets/firefoxreality-1-win10-64/bootstrap.ps1, imagesets/generic-worker-ubuntu-18-04-podman/bootstrap.sh, imagesets/generic-worker-ubuntu-18-04-staging/bootstrap.sh, imagesets/generic-worker-ubuntu-18-04/bootstrap.sh, imagesets/generic-worker-win2012r2-staging/bootstrap.ps1, imagesets/generic-worker-win2012r2/bootstrap.ps1, imagesets/generic-worker-win2016/bootstrap.ps1
Eventually, these updates should be automatic, but for now, I thought good to update manually.
Note, I'll create a separate PR (or Issue) for downloading the new monorepo taskcluster-worker binaries. At the moment, the `bootstrap.ps1` and `bootstrap.sh` scripts still download taskcluster-worker-runner release binaries from the old repo.
=> Upgrade all image sets to generic-worker v28.0.0

config/projects/relman.yml
I'd need a Windows image containing Visual Studio Build Tools.
I have three options:
1) Set up a new imageset specific for my task;
2) Use the deepspeech image;
3) Add Visual Studio Build Tools to the generic image.
1 seems overkill, given that (at least for now) it will be used by a single task in a single project.
2 is super-easy, but might be unstable (there's no guarantee they will keep what I need).
3 would be easy, but would increase the size of the generic image and might have side effects in other projects using the same image (although I think there is low chance there will be side effects).
I think between the three options I prefer the second, because the task is not sensitive and it's OK if it's broken for a few days.
=> Use the deepspeech Windows imageset for win2012r2 relman workers

config/imagesets.yml, config/projects/taskcluster.yml, config/projects/wpt.yml
I notice that the last image used here was not the `community` variant. Should we always be using the community variant here?
=> Update community image to drop invalid packets for wpt#21529

imagesets/deepspeech-win2012r2-b/bootstrap.ps1, imagesets/deepspeech-win2012r2-gpu-b/bootstrap.ps1, imagesets/deepspeech-win2012r2-gpu/bootstrap.ps1, imagesets/deepspeech-win2012r2/bootstrap.ps1, imagesets/firefoxreality-1-win10-64/bootstrap.ps1, imagesets/generic-worker-ubuntu-18-04-podman/bootstrap.sh, imagesets/generic-worker-ubuntu-18-04-staging/bootstrap.sh, imagesets/generic-worker-ubuntu-18-04/bootstrap.sh, imagesets/generic-worker-win2012r2-staging/bootstrap.ps1, imagesets/generic-worker-win2012r2/bootstrap.ps1, imagesets/generic-worker-win2016/bootstrap.ps1
We should probably do this automatically moving forward, however we might want to implement that as part of the worker deployment automation project. Also, until taskcluster-proxy and livelog are fully migrated into the monorepo, this might need some tweaks before we can automate everything cleanly.
=> Upgrade generic-worker imagesets to use taskcluster v29.2.0 binaries

config/projects/taskcluster.yml
This seems to have a lot more permissions and secrets available than our
normal monorepo tasks. docker-worker did not allow public PRs and
monorepo does. I'm decently sure that we can allow it but I want
to take a closer look first.
This supports taskcluster/taskcluster#2775
=> Add d-w ci permissions to monorepo

config/projects/taskcluster.yml
This separates the workers that allow privileged and disableSeccomp
features to only run a subset of the tests.
=> Set up docker-worker CI workers that allow priv

config/projects/taskcluster.yml
I'm not sure how to test this but I was hoping it would fix https://community-tc.services.mozilla.com/tasks/dodXkKPbQ2qBAXa59aSx5A/runs/0/logs/https%3A%2F%2Fcommunity-tc.services.mozilla.com%2Fapi%2Fqueue%2Fv1%2Ftask%2FdodXkKPbQ2qBAXa59aSx5A%2Fruns%2F0%2Fartifacts%2Fpublic%2Flogs%2Flive.log#L2583-2598
This bug was introduced after https://github.com/mozilla/community-tc-config/commit/755e466cdf957fbf985fee65b81bb71351443057.
=> Add grants to docker-worker role

config/grants.yml
WPT is moving towards using the checks API for TaskCluster. However we
also use a decision task and as per https://github.com/mozilla/community-tc-config/pull/129
this requires us to be added to the route workaround.
Note that wpt-tc-checks is a temporary clone of wpt being used as we
develop the TaskCluster Checks integration; ultimately this will be
replaced with the wpt repo itself.
=> Add web-platform-tests/wpt-tc-checks to the checks/statuses workaround

config/projects/wpt.yml
The wpt-tc-checks repo is a temporary* clone of wpt, used to develop our
necessary integration to switch from TaskCluster statuses to checks. To
let TaskCluster run on it, it needs the same grants as wpt.
* Temporary here means O(weeks); the hardest part of this project will
be fixing wpt.fyi to work with the checks API and I expect that to take
me a few weeks.
=> Grant wpt-tc-checks the same scopes as wpt

config/projects/taskcluster.yml
```diff
--- current
+++ generated
@@ -919,16 +919,24 @@ Role=login-identity:github/485789|staktrace:
Role=login-identity:github/485789|staktrace:
roleId: login-identity:github/485789|staktrace
description:
*DO NOT EDIT* - This resource is configured automatically.
scopes: - assume:project-admin:webrender
+  Role=login-identity:github/54458|catlee:
+    roleId: login-identity:github/54458|catlee
+    description:
+      *DO NOT EDIT* - This resource is configured automatically.
+
+
+    scopes: - assume:project:taskcluster:docker-worker-tester
+
Role=project-admin:*:
roleId: project-admin:*
description:
*DO NOT EDIT* - This resource is configured automatically.
scopes:
- assume:hook-id:project-<..>/*
```
=> Add d-w test scopes for catlee

config/projects/fuzzing.yml
- hostSharedMemory because running multiple ASan builds reliably in docker requires it
- privileged because some of our containers modify kernel parameters such as `kernel.core_pattern`
=> Add docker-worker capability scopes necessary for fuzzing.

config/projects/firefoxreality.yml
The end goal here is to have a magic link `https://community-tc.services.mozilla.com/tasks/index/project/firefoxreality/master` which would contain the artifacts from the latest master build. So this is for the task that is run on master branch upon pushes (lemme know if you think the scope or the role are not correct pls!)
=> Add taskcluster-index scopes for FxR

config/projects/bergamot.yml, config/projects/cia.yml, config/projects/misc.yml, config/projects/relman.yml, config/projects/servo.yml, config/projects/taskcluster.yml, config/projects/wpt.yml
This will have the side-effect of slightly longer run times as we wait
for workers to be provisioned, but looking at the costs for time spent
idle, it would be hard to justify *not* making this change.
I've also explicitly added the minCapacity in some places where it was
missing (e.g. projects/taskcluster) instead of relying on the default
behavior. This will make it clearer when we look back when the change
was made.
While not stricly necessary, I've also reduced the maxCapacity for many
worker pools. The volume of jobs just doesn't justify the previous
requested max values.
=> Reduce minCapacity to 0 everywhere

config/imagesets.yml, config/projects/relman.yml, config/projects/taskcluster.yml, generate/workers.py
Fixes #282 
Also increases the relman timeouts to 1 second to avoid previous hangs we've seen with a 0 second timeout.
=> Reduce default idle timeout to 1 second for all worker types

config/imagesets.yml, config/projects/relman.yml, generate/workers.py
Accounts for taskcluster/taskcluster#2969
```
! WorkerPool=proj-bergamot/ci-linux (changed: config)                                                    
! WorkerPool=proj-bergamot/ci-windows (changed: config)                                                  
! WorkerPool=proj-bors-ng/ci (changed: config)                                                           
! WorkerPool=proj-cia/ci (changed: config)
! WorkerPool=proj-deepspeech/ci (changed: config)                                                        
! WorkerPool=proj-deepspeech/win (changed: config)                                                       
! WorkerPool=proj-deepspeech/win-b (changed: config) 
! WorkerPool=proj-deepspeech/win-gpu (changed: config)  
! WorkerPool=proj-deepspeech/win-gpu-b (changed: config) …
```
=> Increase idle timeout to account for taskcluster/taskcluster#2969

config/projects/fuzzing.yml, generate/projects.py
We want the CI for domino-web-tests to run on any change to the domino or gridl repositories in their respective master branches. This is intended to function as a dashboard for compatibility of ongoing development in the domino & gridl repos, but should not be blocking CI in either of those.
The `mozillasecurity/domino-web-tests:latest` image will just create a commit in the domino-web-tests repo to trigger CI via `.taskcluster.yml` in that repo.
=> Add a hook to trigger ci in domino-web-tests

config/projects/fuzzing.yml
This is currently working, but the role needs to exist in community-tc for our automated fuzzing tc-admin setup to ignore it.
=> Update domino-web-tests hook and role.

config/grants.yml
WPT is moving towards using the checks API for TaskCluster. However we
also use a decision task and as per #129
this requires us to be added to the route workaround.
Note that wpt-tc-checks is a temporary clone of wpt being used as we
develop the TaskCluster Checks integration; it will be removed once
we've confirmed that the migration works.
=> Add web-platform-tests/wpt to the checks/statuses workaround

config/projects/wpt.yml
WPT intends to add a sink task to their dependency graph, as part of
their migration to the GitHub Checks API. As this task is a do-nothing,
it should use built-in/success, but this requires extended grants.
=> Allow WPT to use built-in/success

config/projects/wpt.yml
It's called `build-in/succeed`, not `built-in/success`, but in either case giving access
to all of built-in seems reasonable.
See https://docs.taskcluster.net/docs/reference/workers/built-in-workers
=> Correct typo in grant for WPT

imagesets/imageset.sh
The test whether an instance type was supported in a region was faulty, since `grep` reads from a file (such as stdin) but the check was passing the input as an argument.
This fix checks for a successful assignment, which in turn requires a 0 exit code for the `aws ec2 run-instances` command.
=> Fix to imageset.sh test whether instance type is supported in region

imagesets/deepspeech-win2012r2-b/bootstrap.ps1, imagesets/deepspeech-win2012r2-gpu-b/bootstrap.ps1, imagesets/deepspeech-win2012r2-gpu/bootstrap.ps1, imagesets/deepspeech-win2012r2/bootstrap.ps1, imagesets/firefoxreality-1-win10-64/bootstrap.ps1, imagesets/generic-worker-ubuntu-18-04-podman/bootstrap.sh, imagesets/generic-worker-ubuntu-18-04/bootstrap.sh, imagesets/generic-worker-win2012r2-staging/bootstrap.ps1, imagesets/generic-worker-win2012r2/bootstrap.ps1, imagesets/generic-worker-win2016/bootstrap.ps1
Note, this also fixes the ubuntu non-staging generic-worker worker types to use the monorepo taskcluster-proxy version.
=> Use TASKCLUSTER_VERSION variable in bootstrap.ps1 scripts

config/imagesets.yml
This updates the AMIs for all the generic-worker workers that I created new images for.
=> Built ec2 images of outdated generic-worker workers

.gitignore, imagesets/imageset.sh
This removes at least one of the pain points of rolling new worker images.
=> Store worker credentials in password store when rolling images

config/projects/fuzzing.yml
* Remove the list of secrets since it's incomplete anyways and we're externally managed.
* Remove podman pool used for experiment.
* Grant `queue:cancel-task:-/*` to decision so we can cancel old tasks.
=> [fuzzing] Clean-up and grant cancel-task to decision.

generate/secret_values.py
I use a yubikey to authenticate secrets access, an it's har to tell
whether I've sufficiently "touched" the yubikey to activate it,
particularly in the winter when my skin is dry.  This log message
will appear immediately after `pass` finishes, giving me the feedback
I need.
=> Log 'Secrets fetched' when fetched

imagesets/imageset.sh
If a given aws region does not support the instance type required for a particular worker type, it is skipped. However, the `imageset.sh` script previously did not check if it was skipped before updating `config/imagesets.yml` and the password store secrets for a given (imageset, region).
Now `imageset.sh` no longer assumes an image is present in a region, and checks first, before applying changes that require the image to exist.
=> Check region secret exists prior to using

config/grants.yml, config/projects/wpt.yml
wpt-tc-checks was a testing-ground repository for wpt as it moved to the
Taskcluster Checks integration. That work has now been completed, and
the repository is no longer needed.
=> [Cleanup] Remove old wpt-tc-checks repository

config/projects/deepspeech.yml
This machine type:
- allows for nested virtualization
- is cheaper (1.5$ -> 1.1471$ ; 0.32$ -> 0.2776$)
- newer and should be faster
- is available in us-east1 and us-east4 zones
So I think it should be an easier switch for the moment than moving to n2d-highcpu-32
=> Use n2-highcpu-32

config/projects/bugbug.yml
As suggested by @djmitche in #319, I'll split the patch in two: one to create the new bugbug project (to be landed right away) and one to remove bugbug from the relman project (to be landed after bugbug is updated to use the worker pool names from the new project).
=> Create a separate configuration for bugbug, with admin from both sallt and cia teams

config/projects/deepspeech.yml
This is hopefully going to help avoid tensorflow linux cuda build failure like:
> Server terminated abruptly (error code: 14, error message: 'Socket closed', log file: '/home/build-user/.bazel_cache/output/server/jvm.out')
=> Update proj-deepspeech/ci workers to 100GB disk

imagesets/README.md, imagesets/docker/Dockerfile, imagesets/docker/TAG, imagesets/docker/build.sh, imagesets/imageset-under-docker.sh, imagesets/imageset.sh
Let's build AWS/GCP images in a predefined docker image, in order to:
a) simplify the process for taskcluster team members
b) ensure preferred versions of tools are used
c) prepare the way for building image sets in automation
Hopefully one day we'll have Windows and Linux generic-worker worker pool machine images building under monopacker and deployable to GCP/AWS/Azure, but until then, this makes sure we have a consistent build environment for the way we do things currently.
In addition, this PR provides a lot more explicit guidance (_better docs_) about the process of building image sets.
=> Build image sets under docker

config/projects/taskcluster.yml
json-e and monopacker have had their branches renamed, but the scopes
weren't updated.  Further, we just dropped support for doing anything
special on pushes to monorepo's main branch.  There's no longer a need
for the old "master" scope for the monorepo, either.
=> Clean up scopes for master->main renames

config/projects/fuzzing.yml
As per the title, this PR creates a hook to trigger runs of the [bugmon-tc](https://github.com/MozillaSecurity/bugmon-tc) project.
=> Add hook and worker pools for bugmon in project fuzzing

config/projects/fuzzing.yml
Adds the required `queue:scheduler-id:-` scope and fixes the cron scheduling to run every 8 hours.
=> Add schedulerId scope and fix scheduling

config/imagesets.yml
These are the images built in
https://github.com/taskcluster/monopacker/pull/85
=> Bug 1665052 - use updated docker-worker images

config/projects/fuzzing.yml
Grizzly is a framework used to run all of our DOM fuzzers. This adds some hooks that will be used for reducing Grizzly testcases to their minimum reproducible size.
`grizzly-reduce-monitor` will eventually run on a schedule, but for now having the hooks in place will aid with testing the underlying images.
=> Add grizzly-reduce hooks

config/projects/misc.yml
This pool has a maxCapacity of 2, and is available to anyone with a GitHub login.  That should minimize the scope of any abuse, and at least give us a user to which to trace the abuse.
=> Add a proj-misc/tutorial pool

config/projects/fuzzing.yml
Orion is the repository used to build all of our docker images for fuzzing.
=> Add scopes for orion repository.

config/projects/misc.yml
This has had a .taskcluster.yml for a long time, but not permission..  I just converted it to v1 for taskcluster/taskcluster#4098.
=> add djmitche/console-taskgraph to the misc project

config/projects/misc.yml
This org just got notices to move away from travis-ci, so let's make the transition to TC a little easier.
=> add blanket proj-misc access to the mozilla-services org

config/projects/relman.yml
All repos that were using Travis CI and are going to use Taskcluster instead.
=> Add more repositories to the relman configuration

config/aws.yml, config/projects/relman.yml
The project admins have the scopes for this but we have to
allow them in via security groups as well.
If this isn't actually desired for the whole pool for all time, let me know.
This is just using the `rdp` sg that was already existing in every region. It
allows all outbound traffic and only RDP on port 3389 for inbound.
cc @marco-c
=> Allow rdp into proj-relman/win2012r2

config/projects/fuzzing.yml
Fixes #371.
The `skipCompressionExtensions` changes in `ci` pool shouldn't be necessary anymore (fixed in https://github.com/taskcluster/taskcluster/issues/3899). I've removed those already.
=> Update fuzzing config to match what is live on community-tc

config/projects/taskcluster.yml
Like the other package registries (aside from pypi), it looks like there's no good way to do a staging publish on crates.io.  There is staging.crates.io, but that appears to be staging for the deployment, not for users.  So this credential is only provided for prod.
=> Add CRATESIO_TOKEN

config/projects/fuzzing.yml
Several secrets were renamed to match our existing naming convention and grant wild cards.  This PR updates those secrets for gr-css.
=> Update secrets for gr-css

config/projects/fuzzing.yml
The reason for the CI increase is that I'm using that queue now for all fuzzing decisions instead of running decisions in the fuzzing work queue.
=> [fuzzing] Increase max CI pool to 20 and grant cancel-task permission for project-fuzzing to fuzzing admins.

config/projects/fuzzing.yml
Wildcards are only valid against suffixes.
=> Fix fuzzing Administrators scope. 

config/projects/taskcluster.yml
Create a task that Poucave can check for completion. See [Poucave issue 851](https://github.com/mozilla-services/poucave/issues/851). Resources stored in [gist 24475309d](https://gist.github.com/jwhitlock/24475309dab548f15cba248dcb98ddef).
=> Add hook project-taskcluster/poucave-issue-851-test

config/projects/taskcluster.yml
Set `metadata.source` to this repo. This change was needed to run the hook, and has already been applied to community-tc.
Change the Telescope URL in descriptions to https://telescope-demo.api.data.allizom.org. This change has not been applied yet.
=> Fixes for hook telescope-periodic-v01

config/projects/taskcluster.yml
This is for the Telescope demo site, adding a client and associated access token. 
GCP Project: mozilla-api-stage
Telescope demo site will be able to make authenticated calls to taskcluster
=> Adding access token configuration for Telescope-Demo site

README.md
Make it clear that root credentials are typically needed to apply changes.
Note, we could probably create a more restricted role that the taskcluster team gets, that allows creation of arbitrary entities that tc-admin controls, but doesn't have scopes to e.g. create tasks.
Or we could have a separate project for community-tc admins, that is different to the taskcluster project, and grant scopes to the community-tc-admins to be able to create all the entities.
But for now I think this is a reasonable solution, since people that run tc-admin should typically have access to the root access token anyway.
=> Added README.md section on how community-tc admins should apply changes

imagesets/docker-worker/bootstrap.sh
This wasn't needed in community, but was needed in firefox-ci - so keeping track of changes here, so we have something more portable.
=> Changes needed for firefox-ci docker-worker images

imagesets/generic-worker-ubuntu-18-04-podman/bootstrap.sh, imagesets/generic-worker-ubuntu-18-04-staging/bootstrap.sh, imagesets/generic-worker-ubuntu-18-04/bootstrap.sh
In 699fd1f8f62b62e2571dfd6ad3724e4fb3fd3e31 we needed to use `shutdown -h now` instead of `shutdown now`, so reflecting that here to be safe.
=> Use `shutdown -h now` instead of `shutdown now`

generate/workers.py
m4.2xlarge is pretty old, and is often unavailable, therefore changing default instance type to m5.2xlarge. See also https://github.com/mozilla/community-tc-config/pull/428#issuecomment-929066262.
Originally I [intended to update](https://github.com/mozilla/community-tc-config/pull/428#issuecomment-930130397) the hardcoded [EC2 availability zones](https://github.com/mozilla/community-tc-config/blob/266a6c02d7d3e6bf86bd192a986355c18266fb23/generate/workers.py#L365-L371)/[GCP zones](https://github.com/mozilla/community-tc-config/blob/266a6c02d7d3e6bf86bd192a986355c18266fb23/generate/workers.py#L269-L278) in this PR. However, I've since seen that I can use [`aws ec2 describe-instance-types`](https://docs.aws.amazon.com/ko_kr/cli/latest/reference/ec2/describe-instance-types.html) and [`gcloud …
=> Default ec2 instance type m4.2xlarge => m5.2xlarge

imagesets/imageset.sh
I hit some issues building GCP images when my default GCP project didn't match the env var [GCP_PROJECT](https://github.com/mozilla/community-tc-config/blob/ffcd9011aabab089ed829f0290f44504e32382c0/imagesets/README.md?plain=1#L65-L67). This PR fixes that issue.
=> Specify the GCP_PROJECT in case it is different to the default project

imagesets/imageset.sh
When using a terminal with a white background colour I could not clearly read text; by explicitly setting background colour the console output should be clear in all terminals now.
=> Explicitly set background console colour to contrast foreground colour

imagesets/README.md, imagesets/imageset.sh
This requirement was [already documented](https://github.com/mozilla/community-tc-config/blob/3ae9b2c05e540a9a2f35336d1058da2e7c8fe8b2/imagesets/README.md?plain=1#L120), but not included in checks.
=> Ensure yq version 3 is used by imageset.sh

config/imagesets.yml, imagesets/imageset.sh
Adding us-east-2 to aws regions to build AMIs in.
Fixes #438.
=> Add region us-east-2 for building AWS EC2 worker AMIs

config/projects/relman.yml
This is needed for https://github.com/mozilla/mozci/pull/546 where we want to build a Docker image on Taskcluster, publish it as an artifact, then index the task so it can later be used to run new tasks.
=> Allow repo mozilla/mozci to index tasks for Docker image publication

config/projects/fuzzing.yml
This hook calls tc-admin which may create other hooks within project-fuzzing, so `assume:hook-id:` is required.
Fixes #447.
=> Restrict scopes of fuzzing hook to avoid circular role definition.

config/projects/taskcluster.yml
See https://github.com/json-e/json-e/issues/430
This leaves JSON-e in the "taskcluster" project.  I think that will be easiest for the moment.
=> add support for the json-e/json-e repository

config/projects/fuzzing.yml
#448 only updated the hook definition, but not the role.
Fixes #447 (again).
=> Update fuzzing role as well as hook.

config/projects/taskcluster.yml
This worker is allowed to repos taskcluster/*, so I missed it in the
earlier PR.
=> Allow the proj-taskcluster/ci worker for json-e

config/projects/mozci.yml, config/projects/relman.yml
Needed for https://github.com/mozilla/mozci/pull/552
This merge requests creates a dedicated project for [mozci](https://github.com/mozilla/mozci/) to:
- run its CI tasks for the github repository (set before in project `relman`)
- create a new hook with a cron schedule to run a decision task
- uses a Docker image stored as an artifact on an [indexed task](https://community-tc.services.mozilla.com/tasks/index/project.mozci.docker.branch/master)
- runs every 15 minutes
- needs scopes to create children tasks
- needs scope to index children task ( as `project.mozci.classification.push.ID`)
=> Setup project mozci with decision task hook

config/projects/mozci.yml
I tested that syntax on a [sample task](https://community-tc.services.mozilla.com/tasks/B1x_y123SPCGRFtYpJvCrQ/runs/0/logs/live/public/logs/live.log)
=> Fix syntax to use indexed docker image in mozci hook

config/projects/mozci.yml
The hook [project-mozci/decision-task-testing](https://community-tc.services.mozilla.com/hooks/project-mozci/decision-task-testing) was missing the previously requested scopes: @marco-c was able to edit the configuration to test that change before creating this PR.
The hook now [runs cleanly](https://community-tc.services.mozilla.com/tasks/groups/JG1XWX3zQLKaKzcA1ysZsQ) with this change
=> Assume defined scopes for hook project-mozci/decision-task-testing

config/projects/mozci.yml
Needed for https://github.com/mozilla/mozci/issues/564
I'm setting up a shared cache for the mozci classification tasks. Pickled payloads using [cachy](https://github.com/sdispater/cachy/) will be stored on that cache : we do not expect a lot of disk storage needed (we do not clone MC ...)
I also need access to a secret in order to configure cache settings for the different tasks.
=> Grant access to docker-worker cache for mozci decision tasks

config/projects/mozci.yml
This MR will update the mozci testing hook to use pushes from autoland instead of mozilla-central.
=> Switch mozci decision task to autoland

config/projects/mozci.yml
In order to preserve the `project/mozci/testing` secret, we do not need to prefix by the project's name
=> Fix project/mozci/testing secret declaration

config/projects/mozci.yml
Needed for https://github.com/mozilla/mozci/issues/618
We need another hook for the project **mozci** that should run once daily, will use the pre-existing secret `project/mozci/testing` and send a few emails through the taskcluster email service + taskcluster proxy.
=> Add mozci daily monitoring hook

config/projects/mozci.yml
As we are wrapping up [initial work](https://github.com/mozilla/mozci/pull/623#pullrequestreview-870579677) on the mozci monitoring hook, we noticed that the command defined here needs some changes.
=> Update mozci monitoring hook command

config/projects/mozci.yml
Sorry, again a fix on the mozci hook, we had a communication issue on that parameter :cry: 
Needed to fix the current error on the hook https://community-tc.services.mozilla.com/tasks/QmrFXEhySYWroLSi6C9cvg/runs/0/logs/public/logs/live.log
=> Use correct mozci date parameter in date hook

config/projects/mozci.yml
Needed for https://github.com/mozilla/mozci/issues/625
We now want to send notifications (emails and matrix notifications) when a mozci classification for a push evolves or is Bad.
=> Enable mozci classification tasks to send emails and matrix notifications

config/projects/mozci.yml
Companion PR of https://github.com/mozilla/mozci/pull/648
This enables a new **production** environment for the mozci project which will use the docker images produced on the `production` branch instead of the `master` (which is still used by `testing`).
=> Setup production environment for mozci project

config/projects/mozci.yml
Followup on https://github.com/mozilla/community-tc-config/pull/465 to enable the correct environment on each hooks
=> Set CLI environments for mozci hooks

config/projects/mozci.yml
Related to https://github.com/mozilla/mozci/issues/647 and https://github.com/mozilla/mozci/issues/608
=> Fix mozci scopes for Matrix notifs + Add 2 flags to monitoring hooks

config/projects/mozci.yml
Now we not only want our tasks to be able to notify at runtime, but we also want to be notified when one of them fails on TaskCluster to address the issue. Related to https://github.com/mozilla/mozci/pull/668 and specifically to the [changes in this file](https://github.com/mozilla/mozci/pull/668/files#diff-8cac448572228d01096cdf0ff1974ce59c381308c18b1c094b0e0f4954a759c5R89).
=> Grant rights to Mozci classification tasks to email analysis team on fail

.taskcluster.yml, imagesets/firefoxreality-1-win10-64/bootstrap.ps1, imagesets/generic-worker-ubuntu-18-04-podman/bootstrap.sh, imagesets/generic-worker-ubuntu-18-04-staging/bootstrap.sh, imagesets/generic-worker-ubuntu-18-04/bootstrap.sh, imagesets/generic-worker-win2012r2-staging/bootstrap.ps1, imagesets/generic-worker-win2012r2/bootstrap.ps1, imagesets/generic-worker-win2016/bootstrap.ps1, imagesets/relman-win2012r2/bootstrap.ps1
Upgrade remaining generic-worker worker pools to v44.8.4.
Note, after this lands, worker pools will still need to be rolled out (machine images built) so merging won't automatically trigger a deploy, currently (future work).
=> Upgrade all generic-worker worker pools to v44.8.4

config/imagesets.yml, imagesets/docker/Dockerfile, imagesets/docker/TAG, imagesets/imageset.sh, imagesets/signin-aws.sh
This is a bit of a cleanup for the issues we discovered today. It does the following:
1) `signin-aws` is now not a system dependency, but is included in the repository. It has been renamed to `signin-aws.sh` to make it clearer that it is just a shell script. Also the name doesn't overload the function name that can be used to source it from the shell, to make it a little more obvious that the function and the executable script are different things.
The idea is that if you source its output, it sets env vars for you for 6 hours, so you don't need to run it every time you build an image set, e.g. you could source its output once to get an AWS session, and then create all image sets, without needing to reauthenticate.
2) The unique ID generation process has changed from using `tr` to using …
=> Fix imageset generation on macOS

imagesets/imageset.sh, imagesets/signin-aws.sh
A few cleanup items here:
1) The generated commit added to the community-tc-config repo when `imageset.sh` is run, is now automatically pushed to github
2) Additional checks when running `imageset.sh` that:
a) no local (uncommitted) changes exist
b) local HEAD commit matches remote `main` branch of mozilla/community-tc-config github repo
3) Exit code cleanup - exit code 65 was used in two places, so renumbered all the exit codes (nothing currently using them, so should be safe to change them)
I can't properly test these changes until they land, since one of the changes is to ensure that current HEAD matches remote `main` branch, and that will fail while these commits haven't made it to the `main` branch. In any case, I'll comment those lines out and check the new git pull/push commands.
=> Push generated git commits to community-tc-config repo

imagesets/imageset.sh
When we added `set -u` this broke. This should fix it.
=> Fix handling of GCP_PROJECT not being set

imagesets/imageset.sh
The `imageset.sh` script builds machine images (expensive, time-consuming) and then updates password store with credentials to connect to new machine images. However, if there is a problem with the password store / gpg setup of the user running `imageset.sh`, they will only discover this after the new machine images have been built.
I added a pre-check that writing secrets to the password store works, before beginning the long process of generating machine images, to reduce chance of failure once the image building process has started.
At the same time, I modified the log routine to clear to end-of-line on line return, so that the background colour extends to the full terminal width on line returns (aesthetic improvement).
I also moved all checks to before the 'Starting!' log line and …
=> Some fix-ups to imageset.sh

imagesets/generic-worker-win2012r2/bootstrap.ps1, imagesets/generic-worker-win2016/bootstrap.ps1
No need to try to run this step when deploying in a different cloud (like google cloud).
The powershell previously would fail silently, but let's not even try to run it if we are in the wrong cloud, and this serves as a reminder to editors of the bootstrap script, that the scripts may need to work in multiple cloud environments.
=> Only run AWS steps when in AWS

config/projects/fuzzing.yml
Scopes for privileged docker were missed in #485. Required for Android emulator in Docker.
I've already applied these manually, so this should be a no-op.
=> Add missing fuzzing scopes.

config/projects/misc.yml
I'm not using it at the moment, and it has recently been failing.
=> Stop running jcristau-fx-release-metrics daily

imagesets/README.md
Looks like I overlooked the README when working on #471... I think this should be accurate now.
The `signin-aws` script was moved into the same directory as the `imageset.sh` script (previously was only part of the docker image) and renamed to `signin-aws.sh`. It is therefore also no longer an external dependency when running `imageset.sh` natively, since it is available in the current directory.
=> Doc fix follow up from #471

imagesets/generic-worker-win2012r2-staging/gcp_filters, imagesets/generic-worker-win2012r2/gcp_filters, imagesets/relman-win2012r2/gcp_filters
Got a warning when building, that the image was deprecated, and that I should use this new one.
=> Update base GCP image for generic-worker-win2012r2-staging

config/projects/mozci.yml
After a discussion with @marco-c we decided to remove the `push` command prefix from the command of the new mozci hook.
There is also a typo in the scopes declaration of both testing & production hooks: the `assume:hook-id` is not the correct one.
We currently have the following error which should be fixed by this PR:
```
The error was:
Error: Client ID static/taskcluster/hooks does not have sufficient scopes and is missing the following scopes:
assume:hook-id:project-mozci/monitoring-testing
This request requires the client to satisfy the following scope expression:
{
"AllOf": [
"assume:hook-id:project-mozci/monitoring-testing",
"queue:create-task:project:none",
"queue:scheduler-id:-",
{
"AnyOf": [
"queue:create-task:highest:proj-mozci/compute-smaller", …
```
=> Remove push command prefix and update assume:hook-id

config/projects/taskcluster.yml
In GCP we are getting error "No user logged in with console session" so moving to AWS.
=> Move gw-ubuntu-20-04-staging from gcp to aws

config/projects/fuzzing.yml
Store entries from `/tmp/grizzly` as artifacts.
=> Add additional artifact path for bugmon hooks

config/projects/fuzzing.yml
Looks like I removed the required `description` parameter from `metadata`.  Without it, this hook cannot be triggered.
=> Add missing metadata description

config/projects/fuzzing.yml
Apologies but it looks like I was also missing scopes to grant access to a required secret.
=> Add missing scopes required by covdiff

config/projects/taskcluster.yml
Currently when we click "re-run" on a failed builds we get an error:
```
Client ID static/taskcluster/github does not have sufficient scopes and is missing the following scopes:
{
"AnyOf": [
"queue:rerun-task:taskcluster-level-1/f0VYFxm8Q9SBeIpBWqCK1Q/GXJkIXslRVSrJ77GrfEYoA",
"queue:rerun-task-in-project:none",
{
"AllOf": [
"queue:rerun-task",
"assume:scheduler-id:taskcluster-level-1/f0VYFxm8Q9SBeIpBWqCK1Q"
]
}
]
}
```
=> Allow to re-run failed tasks from github

config/projects/fuzzing.yml
We're seeing many task failures since enabling fuzzing on GPU instances because we later try to reduce those crashes on non-GPU instances.
=> Use GPU instances for Grizzly reducer Windows pool.

config/projects/taskcluster.yml
I believe this is what's required for the docker-worker tests run in https://github.com/taskcluster/taskcluster/pull/5695
=> Add disableSeccomp scope to docker-worker-tester

config/imagesets.yml
Fixes #516.
Built using [monopacker](https://github.com/taskcluster/monopacker/tree/matt-boris/updateDockerWorker).
=> build(AMI): update docker worker AMIs on AWS (for #516)

config/projects/taskcluster.yml
The docker-worker _config setting_ to say whether the worker accepts tasks that use the `disableSeccomp` feature is `allowDisableSeccomp`.
=> Fix docker-worker config for disableSeccomp feature in proj-taskcluster/dw-ci worker pool

config/imagesets.yml
Fixes #517.
Upgraded both GCP and AWS images to v44.23.0. These new images also include the correct certs for livelog.
Built using [monopacker](https://github.com/taskcluster/monopacker/tree/matt-boris/updateDockerWorker).
=>  build(AMI): update docker worker image on GCP (for #517)

config/projects/fuzzing.yml
We have indexed tasks that infrequently change, but must exist as long as they are defined in Orion. This will check if any Orion indexed tasks are about to expire, and rebuild them to refresh the index. (added to Orion [here](https://github.com/MozillaSecurity/orion/pull/215/commits/b5f230a4efd557fcdc054dfcab68f9692219e3aa))
The `index:insert-task:project.fuzzing.orion.*` scope is not related, but will be needed for another Orion change (https://github.com/MozillaSecurity/orion/issues/111).
=> Add hook to run Orion rebuild decision weekly.

config/projects/fuzzing.yml
Fixes after testing #528. Applying should be a no-op.
=> Fix Orion hook scopes and definition after live testing.

config/projects/fuzzing.yml
Although the audio/video issues have not been resolved on aws, the `bugmon-pernosco` pool must use aws (due to the bare-metal requirement).  This pool will not actually be enabled via the hook until the audio/video issues have been resolved.
Additionally, the `bugmon-processor` pool should use gcp.
=> Move bugmon-processor to gcp and bugmon-pernosco to aws

config/projects/taskcluster.yml
This should allow me to
* create tasks in a test task queue, for a specific projectId
* create a worker polling that task queue
Depending on the configuration of the object service, this may or may not be able to create objects -- we'll see!
=> Add a role for testing #5777

config/imagesets.yml
This creates a new imageset based off of v44.23.4 to include the `disableSeccomp` feature.
cc: @jschwartzentruber @pyoor
=> Create legacy docker worker imageset based on v44.23.4 for disableSeccomp feature

config/projects/firefoxreality.yml, config/projects/git-cinnabar.yml
Due to the changes in github service of Taskcluster, we need to adjust few roles here.
There are just two projects who defined separate `:release` roles, so in order to keep it working we'd need to merge this one right after we make a release to community.
Please see https://github.com/taskcluster/taskcluster/pull/5940
=> New roles would be assumed for releases

config/aws.yml, config/projects/fuzzing.yml, config/projects/relman.yml, config/projects/taskcluster.yml, generate/workers.py, imagesets/generic-worker-win2016-amd/bootstrap.ps1, imagesets/generic-worker-win2022/bootstrap.ps1
It might be easiest to review the commits in sequence. This PR fixes the installation of an ssh daemon on the Windows workers (for everyone) but only applies the ssh security group to the proj-taskcluster Windows workers running in AWS. This should make it possible to ssh onto Windows workers when there are problems. It was already possible to RDP onto them.
Note, this required a fix to the python code to allow workers to be in more than one security group.
Thanks!
=> Enable sshd on proj-taskcluster windows workers

imagesets/generic-worker-ubuntu-22-04-staging/bootstrap.sh, imagesets/generic-worker-ubuntu-22-04/bootstrap.sh, imagesets/generic-worker-win2022/bootstrap.ps1, imagesets/imageset.sh, imagesets/relman-win2012r2/bootstrap.ps1
~~`gcc` appears to be required to fix the CI failure from https://github.com/taskcluster/taskcluster/pull/6050.~~
From https://go.dev/doc/go1.20:
>On Linux and other Unix systems, and on Windows, a host C toolchain is required to use the race detector.
Edit: I'll try to fix this in a later PR.
This change also clones the passwordstore from its new repo. Please follow these instructions to get it to work for you @petemoore and @lotas (@hwine too if you'd like to set it up).
```bash
#
#
#
```
View updated readme [here](https://source.cloud.google.com/taskcluster-passwords/secrets).
=> Bump tc version to latest and update passwordstore location

imagesets/generic-worker-ubuntu-22-04-staging/bootstrap.sh, imagesets/generic-worker-ubuntu-22-04/bootstrap.sh, imagesets/generic-worker-win2016-amd/bootstrap.ps1, imagesets/generic-worker-win2022/bootstrap.ps1, imagesets/relman-win2012r2/bootstrap.ps1
This is useful for testing https://bugzilla.mozilla.org/show_bug.cgi?id=1815711 on Windows, and keeps everything else up-to-date at the same time.
=> Update all worker pools to generic-worker 49.1.2

config/projects/taskcluster.yml
Needed for automatic cancellation of previous unresolved tasks in taskcluster PRs when a new push is made to a branch with an associated PR.
=> Add scopes for cancelling/sealing taskcluster-level-1 task groups to taskcluster github repos

imagesets/generic-worker-win2022/bootstrap.ps1, imagesets/relman-win2012r2/bootstrap.ps1
I think this is valuable in general, so applying to both the generic image and the relman specific one.
=> Disable AV and disk indexing in Windows images for improved performance

imagesets/relman-win2012r2/aws_filters, imagesets/relman-win2012r2/gcp_filters
Note, if this works, and fixes the issue, we should rename the image set directory and the worker pool name to reflect the updated version of Windows. But since this might not work, haven't done that yet (will affect the .taskcluster.yml files that specify the worker pool too).
@marco-c Can you take a look and let me know what you think?
=> Migrate relman machine image from Windows Server 2012 R2 to Windows Server 2022

config/imagesets.yml
This should fix livelog on this imageset.
CC @marco-c
=> Configure locations of livelog and taskcluser-proxy on relman-win2022

config/projects/taskcluster.yml
This aligns with the namespace used by docker-worker tests ([garbage.docker-worker-tests](https://community-tc.services.mozilla.com/tasks/index/garbage.docker-worker-tests)).
This will be used for the tests I am adding to the generic-worker mounts feature for Indexed Artifact content (feature added in https://github.com/taskcluster/taskcluster/pull/6246 and released in [taskcluster v51.0.0](https://github.com/taskcluster/taskcluster/releases/tag/v51.0.0)).
This feature was broken in 51.0.0 and a fix was created in https://github.com/taskcluster/taskcluster/pull/6264 but tests are still required, hence the change to the scopes here, as the first step in creating the new tests.
=> Grant generic-worker-tester scopes for reading/writing to Index

config/projects/taskcluster.yml
We have e.g. two distinct Windows worker pools in proj-taskcluster:
* proj-taskcluster/gw-ci-windows-2022 (privileged - tasks run as LocalSystem)
* proj-taskcluster/gw-windows-2022 (regular - tasks run as regular task users)
The first pool is intended for generic-worker CI, which when testing generic worker, needs to be able to create OS users on the fly.
The second pool is a regular pool, for running tasks as normal.
Both pools should be used by the monorepo CI. For example, testing worker runner on windows does not require extra privileges, but testing generic-worker on windows does.
Rather than maintain a list of specific proj-taskcluster worker pools that are allowed, it seems reasonable to allow the CI to use any of the proj-taskcluster worker pools. This should help reduce burden in …
=> Allow taskcluster CI to use any proj-taskcluster worker pools

config/projects/taskcluster.yml
In https://github.com/taskcluster/taskcluster/pull/6183 a test was updated, requiring scope `generic-worker:cache:apple-cache`. Since CI was only running against mocks, and `GW_TESTS_USE_EXTERNAL_TASKCLUSTER` was broken (currently being fixed in https://github.com/taskcluster/taskcluster/pull/6274), it was not noticed that the scope needed to be added to role `project:taskcluster:generic-worker-tester`.
=> How do you like them apples?

imagesets/generic-worker-ubuntu-22-04-staging/bootstrap.sh, imagesets/generic-worker-ubuntu-22-04/bootstrap.sh
AWS has this kernel module by default. We will then, in generic worker, run:
```bash
modprobe v4l2loopback video_nr=0
chmod 660 /dev/video0
chown root:<taskUser> /dev/video0
```
so that the `/dev/video0` device is available to the task user.
=> Install v4l2loopback for gcp

config/projects/taskcluster.yml
Now that we're shifting more CI tasks to this pool, I think it's appropriate to increase the max capacity to 20 for now.
=> increase max capacity of gw-ubuntu-22-04 pool to 20

imagesets/generic-worker-win2022/bootstrap.ps1
Needed to install gcc for the race detector to work on windows.
=> chore: bump deps and install gcc on win2022

config/projects/git-cinnabar.yml
- osx-10-10 worker type has been unused for at least two years.
- osx worker type moved to Github Actions (although they still use a "travis" prefix in their workerId)
- Add a linux pool with generic-worker to start/attempt a migration off docker-worker.
=> Adjust proj-git-cinnabar workers

config/projects/git-cinnabar.yml
The migration to generic-worker is complete.
=> Remove proj-git-cinnabar docker-worker pool

config/projects/taskcluster.yml
Pretty trivial fix - just wanted to highlight that this worker pool isn't for _all_ CI tasks, only for the Generic Worker CI tasks. It could have looked like it was for all CI tasks, but not other proj-taskcluster tasks, which isn't the case.
=> minor doc fix

generate/workers.py
Fixes #626 
Static workers don't fetch their config from Worker Manager (although, they probably should). In the current design, the configuration of the worker only lives on the worker itself, and isn't centrally managed. Just because the worker isn't provisioned by Worker Manager, it would still be possible for Worker Manager to manage its config, but that is another story.
Anyway, since Worker Manager doesn't know e.g. what the value of the Generic Worker config setting `sentryProject` is on a particular Generic Worker worker, it can't know what Sentry scope to grant role `worker-pool:<worker pool>`. Currently it therefore doesn't grant any Sentry scope to static worker pools.
We consistently use Sentry project `generic-worker` for Generic Worker workers, and Sentry project …
=> Issue 626: grant default sentry project scope to static worker pools

imagesets/generic-worker-ubuntu-22-04-staging/bootstrap.sh
Required for https://github.com/taskcluster/taskcluster/pull/6419.
=> chore: switch default kernel on aws to install snd-aloop module

config/projects/taskcluster.yml
Note, this renames the existing staging pool in AWS, but I think that is ok, because I don't think anything references it.
Now we'll have two pools, and then worker pool name will show whether it is running in aws or google/gcp.
=> proj-tascluster generic-worker staging pool also for google/gcp

imagesets/generic-worker-ubuntu-22-04-staging/bootstrap.sh
Reverts mozilla/community-tc-config#633
Not going to worry about getting this working on AWS. The kernel module is installable on GCP, so we'll shift our pool in that direction.
=> Revert "chore: switch default kernel on aws to install snd-aloop module"

config/projects/misc.yml, config/projects/taskcluster.yml
The `generic-worker:loopback-audio` scope is needed for https://github.com/taskcluster/taskcluster/pull/6419.
=> chore: add audio scope and switch over to gcp

config/projects/relman.yml
Hi @marco-c
It shouldn't be necessary to run tasks as root, since podman does not require permissions to use --privileged flag.
This also adds back docker-worker cache scopes to hooks, since hooks seem to be generated dynamically (I can't find them in this repo) so whatever creates the hooks probably include docker-worker scopes, so the hook-id roles need to have them.
For the repo roles, I didn't add docker-worker scopes back, because I preferred to just change them in the .taskcluster.yml file of the repo directly, and with a little bit of effort, we can switch the task definitions to native generic worker tasks, so you don't rely on the d2g translation layer. That is nice, because we'd like to get rid of it at some point, and it means you can continue to add generic-worker features to …
=> Fix hooks scopes and don't run tasks as root in worker pool proj-relman/ci

config/projects/relman.yml
See https://github.com/taskcluster/taskcluster/issues/6475 for context. Payloads are broken under Generic Worker, so moving relman back to Docker Worker until we've fixed the underlying issue, and rolled out to production.
=> Move relman back to Docker Worker

imagesets/generic-worker-ubuntu-22-04/bootstrap.sh
This is not as scary as it sounds. This enables a VMware compatible interface in kvm, which is [needed for some fuzzing tasks](https://github.com/AFLplusplus/AFLplusplus/blob/stable/nyx_mode/README.md#fuzzing-with-nyx-mode).
Some very low-level explanation of the feature here: https://www.spinics.net/lists/kvm/msg160883.html
=> Add kvm.enable_vmware_backdoor modprobe option for Ubuntu x86-64.

config/projects/fuzzing.yml
This is needed so I can begin testing g-w tasks in proj-fuzzing (I don't have scopes to launch tasks until this is added to a MozillaSecurity repo).
=> Add generic-worker capability scopes for fuzzing-tc-config

generate/workers.py
Spot instances in GCP are documented here: https://cloud.google.com/compute/docs/instances/create-use-spot#api
We've been using these in fuzzing pools for some time without issue, although I have no access to the GCP console to confirm we're really getting spot instances.
=> Switch to spot instances in GCP.

config/projects/fuzzing.yml
The intention is to migrate docker-worker tasks from `proj-fuzzing/ci`  to use d2g in this pool.
=> Add a Fuzzing CI pool for generic-worker migration.

config/imagesets.yml, config/projects/mozci.yml
This was the last remaining worker pool using this Generic Worker image set.
This PR moves the worker pool to GCP and removes the AWS config of the image set.
CC @marco-c
Note, the worker pool was using m5.2xlarge in AWS, which is marketed as general purpose, 8 vCPUs, 32 GB RAM:
* https://aws.amazon.com/ec2/instance-types/m5/
In GCP this looks roughly equivalent to c3-standard-8:
* https://cloud.google.com/compute/docs/general-purpose-machines#c3_series
I didn't research spot price differences.
=> Move proj-mozci/generic-worker-ubuntu-22-04 from aws to gcp

config/projects/bugbug.yml
@marco-c I think this is safe to remove for now. Does this look fine to you? The tasks will still have root access from _within_ the container with podman. Please let us know if you run into any issues without this config.
=> chore: remove unneeded (likely?) worker config

imagesets/docker-worker/gcp_base_instance_type
Looks like I forgot to commit this file when building docker-worker image on gcp. Whoops.
=> Add missing file imagesets/docker-worker/gcp_base_instance_type

imagesets/generic-worker-win2022/bootstrap.ps1
This is the command that RelOps suggested using.
Fixes #681
=> Issue 681 - completely uninstall Windows Defender on Windows Server 2022

imagesets/generic-worker-win2022/bootstrap.ps1
Around two years ago, in #444, additional code was added to work around a networking issue discovered on Windows Server 2016 in AWS. The PR conversation provides additional context.
It appears this issue no longer exists on Windows Server 2022, so the code can now be removed.
I discovered this when viewing the `bootstrap.ps1` standard error output in https://community.taskcluster-artifacts.net/HCP-7izRQ-GYybUCxYqhOA/0/public/logs/EC2Launch2911653372/err.tmp
```
C:\ProgramData\Amazon\EC2-Windows\Launch\Scripts\InitializeInstance.ps1 : The term 
'C:\ProgramData\Amazon\EC2-Windows\Launch\Scripts\InitializeInstance.ps1' is not recognized as the 
name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or 
if a path was included, verify that the path is …
```
=> Code removed that is not needed on Windows Server 2022

config/projects/relman.yml
We are using it in place of 'ci' in code-coverage and code-review, and 'ci' had 50 as max capacity.
=> Bump proj-relman/generic-worker-ubuntu-22-04 worker's max capacity to 50

config/projects/relman.yml
Forgot to add after switching code-coverage, code-review repos to us checks api
=> Added `queue:route:checks` to relman projects

.taskcluster.yml, config/projects/fuzzing.yml
Updated .taskcluster.yml provisioner to allow `proj-taskcluster/ci` workers to pick up tasks (instead of `proj-misc/ci`)
Updates community-tc-config hook after migration
=> Fix pipelines

config/grants.yml
@marco-c I've already applied this. Please check and see if this fixes your access to the generic worker private artifact for interactive sessions.
Here's the github team https://github.com/orgs/mozilla/teams/ci-and-quality-tools.
=> chore: add gw interactive artifact permissions and allow ci/quality tools

imagesets/generic-worker-win2022/bootstrap.ps1
This service is meant to improve performance over time. In the short term it consumes compute resources. This is not helpful for fuzzing and likely any other use case.
=> Disable SysMain (Superfetch) to improve performance

config/imagesets.yml
@tysmith @jschwartzentruber please confirm this updated config works and we'll get this landed. The config has already been applied.
Fixes https://github.com/taskcluster/community-tc-config/issues/695.
=> chore: add binary locations to win2016 worker config

config/imagesets.yml, imagesets/generic-worker-ubuntu-22-04-staging/bootstrap.sh, imagesets/generic-worker-ubuntu-22-04/bootstrap.sh
Until now we've only configured vKMS on Linux workers if they are running GCP, not in other clouds.
Testing AWS staging Ubuntu using the same technique as used with GCP in #709 in this PR.
Currently AWS staging [is using](https://community-tc.services.mozilla.com/tasks/WRw6TLQwT1-bHycctYV7Aw/runs/0/logs/public/logs/live.log#L34) an X11 graphical backend rather than DRM.
=> Install Linux extra modules and configure vKMS for all cloud providers

config/projects/taskcluster.yml
Currently getting a lot of errors in https://community-tc.services.mozilla.com/worker-manager/proj-taskcluster%2Fgw-ubuntu-22-04/errors
Hopefully with this setting, workers will stay alive long enough for us to grab logs or execute commands on them to see what is wrong. Then we can disable afterwards.
=> Temporarily disable shutdowns after panic in proj-taskcluster/gw-ubuntu-22-04

config/projects/misc.yml
No good reason to have this so restrictive. If more than one person is studying the tutorial at a time, they can totally block each other, making it a deterrent rather than an incentive to use taskcluster.
=> Increase max capacity of proj-misc/tutorial

config/projects/fuzzing.yml
@pyoor Generic Worker can now run Docker Worker task payloads, so this _should_ work. It looks like these were set to legacy version of Docker Worker in #552 but the reason for the change isn't clear from the PR conversation, so I'm not sure what the problems were with the regular Docker Worker images.
In any case, Generic Worker should emulate all of the Docker Worker features, so hopefully things should Just Work™ with this change.
@matt-boris Do you remember why legacy was required over the standard images?
=> Migrate bugmon from Docker Worker to Generic Worker

config/projects/git-cinnabar.yml
I'm having some OOM issues with n2-standard-4, let's try with n2-highmem-4, which has the same number of vCPUs, but twice the amount of memory.
=> Change machine type for git-cinnabar linux workers

config/projects/fuzzing.yml
This will make ci-gw unnecessary, but we'll have to migrate tasks back to ci before removing it.
=> Switch proj-fuzzing/ci to generic-worker

config/projects/taskcluster.yml
Will be used in our monorepo's CI.
=> chore: add `ci` azure worker pool to taskcluster proj

config/projects/fuzzing.yml
@pyoor recently tried to add notifications to our fuzzing pools managed by tc-admin in the fuzzing-tc-config repo, and was hit with missing scopes. This will allow any notification routes to be created in fuzzing roles by that repo.
=> Allow any notification routes in fuzzing tasks

config/projects/taskcluster.yml
This replaces `proj-taskcluster/gw(-ci)-windows-2022` pools with what we had in `proj-taskcluster/gw(-ci)-windows-2022-azure` pools and removes the `proj-taskcluster/gw(-ci)-windows-2022-azure` pools altogether.
As part of the migration effort from AWS to Azure, we shouldn't really need to maintain AWS and Azure versions anymore, and can just standardise on the Azure versions.
=> No need to keep the AWS proj-taskcluster Windows 2022 pools

config/imagesets.yml, config/projects/taskcluster.yml, imagesets/generic-worker-win2022-gpu/aws_base_instance_type, imagesets/generic-worker-win2022-gpu/aws_filters, imagesets/generic-worker-win2022-gpu/aws_owners, imagesets/generic-worker-win2022-gpu/azure_base_instance_type, imagesets/generic-worker-win2022-gpu/azure_image, imagesets/generic-worker-win2022-gpu/bootstrap.ps1, imagesets/generic-worker-win2022-gpu/sysprep.ps1, imagesets/generic-worker-win2022/azure_image, imagesets/generic-worker-win2022/bootstrap.ps1, imagesets/imageset.sh
This updates the images to the latest ones built, and adds a new Windows Server 2022 image set and proj-taskcluster worker pool to use it. The image set is in Azure, is essentially the same as the existing Windows 2022 image set, but additionally has an NVIDIA GPU driver installed. Note, the bootstrap script is shared between the Windows 2022 image sets, and at runtime the script determines if an NVIDIA GPU is present, and installs the driver if one is. This helps to avoid copy/paste between powershell scripts, so that we still only have a single powershell script for bootstrapping our Windows workers.
=> New taskcluster Windows GPU pool in Azure

config/projects/fuzzing.yml
From @jschwartzentruber:
> Just had a thought: you can switch proj-fuzzing/grizzly-reduce-worker to use generic worker and that will test that grizzly runs under d2g. That pool is defined in community-tc-config and frequently has a backlog, so it would be an easy one to test.
=> Move proj-fuzzing/grizzly-reduce-worker from docker-worker to generic-worker

config/projects/mozci.yml
Because the decision tasks of the mozCI project started to cause high load on the Treeherder server with their requests,  the interval got reduced manually to every hour. Deployments (?) reset the value to the in-tree configuration. @marco-c is aware of this change.
=> Reduce mozCI decision task interval to every hour

imagesets/imageset.sh
This helps avoid getting HTTP 401 when querying metadata service in EC2, if the base image that we build our AMIs from has IMDSv2 enforced.
=> Ensure IMDSv1 is enabled in AWS since worker-runner requires it

config/projects/misc.yml, config/projects/taskcluster.yml
=> Use c5.metal in proj-taskcluster/gw-ubuntu-24-04-aws and not in proj-misc/tutorial

config/imagesets.yml, config/projects/taskcluster.yml, imagesets/generic-worker-win2022-staging/azure_base_instance_type, imagesets/generic-worker-win2022-staging/azure_image, imagesets/generic-worker-win2022-staging/bootstrap.ps1, imagesets/generic-worker-win2022-staging/sysprep.ps1
This adds a staging Windows Server 2022 image set and worker pool that uses it, in order to test making changes to Windows Server 2022 bootstrap script, without needing to roll out to production.
We already had this for Ubuntu 22.04.
=> Staging Windows Server 2022 image set and worker pool for testing Windows fixes

.taskcluster.yml, generate/workers.py
I spotted that `black` was reporting formatting issues but CI task was passing. This PR has two commits. The first one fixes the code format failure reporting (so commit should fail CI) and the second commit formats the code, and should pass.
=> Fix black check to have non-zero exit code if formatting required

imagesets/generic-worker-ubuntu-22-04-arm64/gcp_filters, imagesets/generic-worker-ubuntu-22-04/gcp_filters, imagesets/generic-worker-ubuntu-24-04/gcp_filters
This should help with problems we were getting like this:
```
2024-06-20T11:05:16.332185+00:00 generic-worker-ubuntu-24-04-kde8op53cqncn7udqclo rsyslogd[754]: rsyslogd: file '/var/log/syslog'[7] write error - see https://www.rsyslog.com/solving-rsyslog-write-errors/ for help OS error: No space left on device [v8.2312.0 try https://www.rsyslog.com/e/2027 ]
2024-06-20T11:05:16.332348+00:00 generic-worker-ubuntu-24-04-kde8op53cqncn7udqclo rsyslogd[754]: rsyslogd: action 'action-3-builtin:omfile' (module 'builtin:omfile') message lost, could not be processed. Check for additional error messages before this one. [v8.2312.0 try https://www.rsyslog.com/e/2027 ]
2024-06-20T11:05:16.332533+00:00 generic-worker-ubuntu-24-04-kde8op53cqncn7udqclo rsyslogd[754]: rsyslogd: file '/var/log/syslog'[7] …
```
=> Increase boot disk sizes to 20GB on GCP instances

config/imagesets.yml, imagesets/generic-worker-win2016-amd/bootstrap.ps1, imagesets/generic-worker-win2022-staging/bootstrap.ps1, imagesets/generic-worker-win2022/bootstrap.ps1
Partially implemented in staging already in PR #752 where a new staging pool was created for Windows. The only change in staging from the original bootstrap script was a change to [this line](https://github.com/taskcluster/community-tc-config/pull/752/files#diff-ef62ab221f06181bde907db8511e274bbdfdb7b1290e05801bd13d8a517fdcf0R153):
```diff
153c153
< [Environment]::SetEnvironmentVariable("PATH", $Env:Path + ";C:\Program Files\Vim\vim80;C:\go\bin;C:\Program Files\Git\cmd;C:\Program Files\nodejs;C:\Program Files\Python311", "Machine")
---
> [Environment]::SetEnvironmentVariable("PATH", [Environment]::GetEnvironmentVariable("PATH", "Machine") + ";C:\Program Files\Vim\vim80;C:\go\bin;C:\Program Files\Git\cmd;C:\Program Files\nodejs;C:\Program Files\Python311", "Machine")
```
The change was to …
=> Fix PATH issues on Windows (do not include Administrator folders)

config/aws.yml, imagesets/imageset.sh, misc/update-azure-machine-types.sh
The previous security groups were removed as part of a security exercise by the Security Infrastructure team in https://mozilla-hub.atlassian.net/browse/INFRASEC-492
I have created new Security Groups by running https://github.com/taskcluster/community-tc-config/blob/34a74b2a69f09072c1f3312c5c780fdfb4ce88b6/misc/aws-worker-vpc-setup.sh
This updates the internal database with the new security group IDs.
=> Replace deleted security groups

config/imagesets.yml
The first time an image set is built, the "placeholder" references are replaced with the actual images. However, not all regions support the machine type used to build the image, so not all regions should be present. This removes the ones where the machine type is not supported (the leftover placeholder entries).
=> Remove regions where instance types are not supported

config/projects/taskcluster.yml
While setting up Ubuntu 24.04 workers, this makes life easier when I submit a task, to avoid needing to wait for a new bare metal worker to spawn each time, which can take up to 20 mins.
=> Longer timeout for Ubuntu 24.04 workers

config/projects/taskcluster.yml
Let's see how this goes.
Not moving staging or arm64 worker pools yet, this is migrating just the non-staging taskcluster project amd64 Ubuntu 22.04 pools.
=> Move taskcluster workloads from Ubuntu 22.04 amd64 to Ubuntu 24.04 amd64

imagesets/signin-aws.sh
When rebuilding all worker pools (e.g. in https://github.com/petemoore/myscrapbook/blob/master/build-gw-images.sh) the aws credentials can timeout, since now with all the azure worker pools we have, 6 hours is often not enough. Note, it would be a lot quicker to build pools in parallel, but for now we build in serial to simplify recovery if things go wrong, and to avoid conflicts between competing updates to imageset.yml or running tc-admin etc. Bumping to 12 hours would probably have been sufficient, but setting to 24 hours should give us some peace in case the process starts taking even longer.
=> Increase signin-aws.sh credential validity duration (6 hours -> 24 hours)

config/projects/fuzzing.yml
Podman 3 has some problems such as https://github.com/containers/podman/issues/16217 which may be the cause of e.g. https://community-tc.services.mozilla.com/tasks/OeEOyk4mRQu1oFX9OOXsNg/runs/0/logs/public/logs/live.log#L69.
```
+ podman run --rm -e TASK_ID -e RUN_ID -e TASKCLUSTER_ROOT_URL --add-host=taskcluster:127.0.0.1 --net=host -e TASKCLUSTER_PROXY_URL=http://localhost:80 -e PROJECT_NAME -e CI_MATRIX -e GITHUB_EVENT -e GITHUB_ACTION -e TASKCLUSTER_NOW mozillasecurity/orion-decision:latest ci-decision -v
[I] Using taskcluster credentials from environment
[I] Taskcluster Proxy enabled
[D] created git repo tmp folder: /tmp/decision-repo-kqnw6g0k
[D] calling: git init
[D] calling: git remote add origin https://github.com/MozillaSecurity/lithium
[D] calling: git fetch -t -q origin …
```
=> Migrate fuzzing Ubuntu 22.04 workers to Ubuntu 24.04 (includes podman upgrade)

config/projects/wpt.yml
@jgraham 
This creates an additional worker pool (`proj-wpt/ci-gw`) for testing the current task payloads against Generic Worker. If everything goes ok, we can update `proj-wpt/ci` to use the same settings, and drop the `proj-wpt/ci-gw` pool. This pool exists only temporarily to assist testing, so as not to interfere with production workloads until we are sure the new pool supports all of the task payloads that the current Docker Worker pool supports.
=> Create ci-gw test pool for checking tasks run ok under Generic Worker

config/projects/fuzzing.yml
We should use a small dedicated pool for fuzzing decision tasks, since `ci` is the catch-all work pool and can be backlogged at times.
=> Create fuzzing decision pool

config/projects/mozci.yml
We are having some problems bringing up the networking on c3-standard-8 machines...
The same machine images work fine on the default instance types, so let's stick with those.
It looks like I set to c3-standard-8 in #674 in order [to match](https://github.com/taskcluster/community-tc-config/pull/674#issue-1884170429) the aws instance types as closely as possible. But I've spoken to @marco-c and he is happy to switch to a different instance type. At the same time, I have raised this with the gcp team [here](https://mozilla.slack.com/archives/C030ME29BEX/p1720610606700509).
=> Stop using c3-standard-8 which is having problems with networking

config/imagesets.yml, config/projects/fuzzing.yml, config/projects/taskcluster.yml, imagesets/generic-worker-ubuntu-24-04-staging/bootstrap.sh
Currently the bugmon-pernosco ProcessorTask tasks, running in Docker Worker in AWS on bare metal workers (m5d.metal) are not running correctly under Generic Worker via d2g.
Example successful task under Docker Worker:
https://community-tc.services.mozilla.com/tasks/GJCZXWDkSf-Dv8rqZrAMSA
Task definition:
```
provisionerId: proj-fuzzing
workerType: bugmon-pernosco
taskQueueId: proj-fuzzing/bugmon-pernosco
schedulerId: '-'
projectId: none
taskGroupId: C0WNIkrsRfe9_esBSPDFZw
dependencies:
- C0WNIkrsRfe9_esBSPDFZw
requires: all-completed
routes:
- notify.email.jkratzer@mozilla.com.on-failed
priority: high
retries: 5
created: '2024-06-03T16:11:44.567Z'
deadline: '2024-06-03T20:11:44.567Z'
expires: '2024-06-10T16:11:44.567Z'
scopes:
- docker-worker:capability:device:hostSharedMemory
- …
```
=> Add test pool for running rr under generic-worker for ProcessorTask (bugmon-pernosco)

setup.py
I'm not sure if there is a more idiomatic way, I don't think we have the renovate bot set up for this repo.
=> Bump dependency versions to latest

imagesets/generic-worker-ubuntu-24-04-staging/bootstrap.sh
This was pulled out yesterday. I've wrapped in an `if` statement so we don't attempt to configure in gcp where kernel does not support snd-aloop.
=> Restore snd-aloop in staging ubuntu 24.04 worker image set, AWS only

imagesets/generic-worker-ubuntu-24-04-staging/bootstrap.sh
https://askubuntu.com/questions/1500473/enabling-networkmanager-makes-systemd-networkd-wait-online-fail
https://bugs.launchpad.net/ubuntu/jammy/+source/systemd/+bug/2036358
=> ubuntu24.04 disable networkd-wait-online in google

config/projects/bors-ng.yml, config/projects/bugbug.yml, config/projects/fuzzing.yml, config/projects/git-cinnabar.yml, config/projects/misc.yml, config/projects/mozci.yml, config/projects/releng.yml, config/projects/relman.yml, config/projects/taskcluster.yml, config/projects/webrender.yml, config/projects/wpt.yml
This returns worker pools back to GCP that were moved to AWS in #795.
=> Migrate workloads back from AWS to GCP now that crisis is averted

config/projects/taskcluster.yml
I've already applied these changes.
=> chore: remove `idleTimeoutSecs` from our default CI pool to conserve resources

config/projects/taskcluster.yml
For https://github.com/taskcluster/taskcluster/pull/7236
I've applied these changes so I can properly test the CI in that PR.
=> chore: add routes needed for taskgraph to build docker images

config/projects/git-cinnabar.yml
This completes the migration, since https://github.com/glandium/git-cinnabar/commit/adb1eed21dcc41ecdb55f1be78176e5f2b79176d landed.
=> Remove proj-git-cinnabar/win2012r2

config/projects/fuzzing.yml
Is there any way to prevent recursion with a hook like this? eg. if this hook itself fails, that will trigger itself and so on. Maybe with a trigger schema?
=> Add log ingestor hook to capture logs from failed fuzzing tasks

config/projects/git-cinnabar.yml, config/projects/relman.yml
See https://learn.microsoft.com/en-us/azure/virtual-machines/ephemeral-os-disks
Since Dv5 family doesn't support premium storage (and thus doesn't support ephemeral OS disks) we should move to Dsv3 which is closely matched, but supports premium storage.
This should prevent the many errors we are seeing here:
* https://community-tc.services.mozilla.com/worker-manager/proj-relman%2Fwin2022/errors
* https://community-tc.services.mozilla.com/worker-manager/proj-git-cinnabar%2Fwindows/errors
=> Migrate Dv5 VM sizes to Dsv3 in order to support ephemeral OS disks

generate/workers.py
Looks like this config value is also allowed on non-Linux workers, even though I think it doesn't apply. We can follow up later to remove it from e.g. Windows workers etc if we want to.
=> Enable D2G everywhere

config/imagesets.yml, config/projects/bugbug.yml, config/projects/mozci.yml, config/projects/relman.yml, config/projects/taskcluster.yml, generate/workers.py, imagesets/generic-worker-win2022-staging/azure_base_instance_type, imagesets/generic-worker-win2022-staging/bootstrap.ps1
This reverts the CUDA changes on Windows Staging (which seems to have broken Windows GPU pools in #830).
Note, this reverts it only from staging, so that we don't test in production (even though production GPU pools are probably broken, it is a good habit to get into).
It might be worth trying one last time to build with the CUDA installation on staging, or alternatively, we could revert on staging, and then use a pool where we run as root, get an RDP session on it, running as root, and see what is going wrong when we manually RDP onto it and execute the installation steps.
Weirdly, the installation seems to happen, but it seems to break the worker somehow, because workers were getting spawned, but not calling Worker Manager to get credentials, as far as I can tell.
At the same time, I …
=> Test reverting of CUDA installation on Windows staging

config/projects/taskcluster.yml
Let's not land this until image building has finished.
This is a pretty scary change! But I think best to test it in proj-taskcluster before imposing it on any other pools.
=> Enable headless on proj-taskcluster worker pools

imagesets/generic-worker-win2022-staging/bootstrap.ps1
It looks like Windows staging was always building from main branch...
=> Windows staging: fix git checkout to respect TASKCLUSTER_REF

imagesets/imageset.sh
Ironically, the password is now slightly less secure (because there are fewer possible permutations), but still easily secure enough.
=> Admin password fix

imagesets/imageset.sh
This makes logs timestamps more consistent with taskcluster logs elsewhere, and timestamps in taskcluster api calls. It should also aid comparing logs on the built images against locally logged timestamps in imageset.sh to understand how the events relate to each other.
=> Output logs in UTC, RFC 3339 format

config/imagesets.yml, imagesets/imageset.sh
Previously this was disabled since it required user interaction, however this was resolved with the setup steps described here:
* https://github.com/taskcluster/community-tc-config/blob/39256b79ef66d378d3973c5a5d16f6dcc8544f98/imagesets/README.md?plain=1#L71-L91
Note, in addition, this should catch issues early when these steps haven't been performed or they were performed too long ago in the past, rather than the script failing at the end.
=> Sign commits made to password store

imagesets/imageset.sh
The `imageset.sh all` functionality used to live in an external repo that checked out community-tc-config, and would take a `BRANCH` parameter to specify which branch of community-tc-config to use. Now that this all lives in community-tc-config repo directly, we only care about the branch we are on, so don't need this var.
=> Fix use of BRANCH

config/imagesets.yml, imagesets/imageset.sh
If we switched instance type, e.g. in staging, to an instance type that didn't exist in some regions, we could end up having workers on old versions in those regions! 😬
=> Completely replace old image sets when a new one is built

imagesets/imageset.sh
Hopefully this will:
* reduce problems due to passphrases expiring
* show reason why we got
```
imageset.sh: 2024-10-11T17:54:55Z: aws: generic-worker-win2022: us-east-1: Cannot deploy in us-east-1 since instance type c4.2xlarge is not supported; skipping.
imageset.sh: 2024-10-11T17:54:56Z: aws: generic-worker-win2022: us-east-2: Cannot deploy in us-east-2 since instance type c4.2xlarge is not supported; skipping.
imageset.sh: 2024-10-11T17:54:56Z: aws: generic-worker-win2022: us-west-1: Cannot deploy in us-west-1 since instance type c4.2xlarge is not supported; skipping.
imageset.sh: 2024-10-11T17:54:57Z: aws: generic-worker-win2022: us-west-2: Cannot deploy in us-west-2 since instance type c4.2xlarge is not supported; skipping.
```
since clearly it wasn't because the instance type …
=> Some tweaks to image set building

imagesets/README.md, imagesets/imageset.sh
I don't think these steps are necessary, so long as you have:
```
default-cache-ttl 86400
max-cache-ttl 86400
```
in your `~/.gnupg/gpg-agent.conf` file
=> chore: remove gpg preset passphrase setup

imagesets/imageset.sh
Otherwise, lots of resources will stick around (affecting quotas, for example) after every build, in azure.
=> fix: delete azure resource groups after build too

config/projects/taskcluster.yml
Needed for new tests in https://github.com/taskcluster/taskcluster/pull/7343.
=> chore: add `docker-worker:capability` scopes and `docker-worker:feature` scopes to gw tester

imagesets/generic-worker-ubuntu-24-04-staging/bootstrap.sh, imagesets/generic-worker-ubuntu-24-04/bootstrap.sh
Cleanup from https://github.com/taskcluster/community-tc-config/pull/887. I hadn't realized we were installing `linux-modules-extra-$(uname -r)` which should be sufficient. I think the fix for GCP is creating the `/etc/modprobe.d/snd-aloop.conf` options file alongside adding `snd-aloop` to `/etc/modules`.
=> chore: small cleanup around installing kernel modules

config/imagesets.yml
This reverts commit dd421e5191ec82a9fbdc41fa8645b4649496de70 which seems to have broken Windows 2022 worker pools.
=> Revert "Built new Azure machine images for imageset generic-worker-win2022"

imagesets/generic-worker-win2022-staging/bootstrap.ps1, imagesets/generic-worker-win2022/bootstrap.ps1
The recent windows image rollout for v77 failed due to the following issue in the install logs:
```powershell
PS>TerminatingError(Invoke-WebRequest): "<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>404 Not Found</title>
</head><body>
<h1>Not Found</h1>
<p>The requested URL was not found on this server.</p>
<hr>
<address>Apache/2.4.29 (Ubuntu) Server at artfiles.org Port 443</address>
</body></html>
"
```
Looking into the artfiles.org download for gvim, I see no more `.exe`s are available to download https://artfiles.org/vim.org/pc/. I think this is safe to remove so we're unblocked for now, as I believe it's only being installed for debugging purposes.
=> fix: remove broken install link for gvim

config/projects/git-cinnabar.yml
I'm interested in testing [taskcluster-github checks](https://docs.taskcluster.net/docs/reference/integrations/github/checks)
=> Add `queue:route:checks` to the git-cinnabar project

config/projects/fuzzing.yml
The underlying data source has been broken for several months and it's not clear when or if it will be fixed.  Removing the hook for now.
=> Remove the covdiff fuzzing hook

imagesets/generic-worker-freebsd/bootstrap.sh, imagesets/generic-worker-ubuntu-24-04-staging/bootstrap.sh, imagesets/generic-worker-ubuntu-24-04/bootstrap.sh, imagesets/generic-worker-win2022-staging/bootstrap.ps1, imagesets/generic-worker-win2022/bootstrap.ps1
This change gets us more in line with what they do for FxCI https://github.com/mozilla-platform-ops/worker-images/blob/main/scripts/linux/ubuntu-2404-amd64-gui/fxci/04-wayland.sh
I've decreased the delay from 30s to 10s and we can go from there.
I've also bumped the taskcluster version and the go binary version downloaded.
=> fix: add gdm3 startup delay to give wayland time 

imagesets/generic-worker-ubuntu-24-04-arm64/gcp_filters, imagesets/generic-worker-ubuntu-24-04/gcp_filters
Simple test was successful on the staging pool first https://community-tc.services.mozilla.com/provisioners/proj-taskcluster/worker-types/gw-ubuntu-staging-google/workers/us-east4-b/3511232623394459624?sortBy=started&sortDirection=desc
https://community-tc.services.mozilla.com/tasks/YR1EIPnfTUCp5pcKU_O6Hw
=> chore: bump base ubuntu image version to v20250130

config/projects/taskcluster.yml
Due to the changes in https://github.com/taskcluster/taskcluster/pull/7505.
We'll also need a PR in the monorepo that points to these newly-named worker pools.
=> chore: remove `runTasksAsCurrentUser` config and rename pools

imagesets/imageset.sh
I don't think this is needed anymore, especially while building our production images for community tc. Seems like a waste of resources.
=> chore: stop building docker worker images during `./imageset.sh all`

config/projects/fuzzing.yml
C3D gives much better performance than N2 for a small price increase.
=> Use GCP C3D machine type for fuzzing/ci pool

config/grants.yml
Since we switched to `schedulerId: fuzzing`, I can't manually re-run fuzzing tasks anymore. I think this fixes it in a generic way.
=> Add rerun scope for project specific schedulers

generate/utils.py, generate/workers.py
Using keyed-by feature from fxci-config
Example usage:
```yaml
workerPools:
wp-azure:
owner: x@x
cloud: azure
..
workerManagerConfig:
initialWeight:
by-location:
west.*: 0.8
us-east-1: 0.3
default: 1
maxCapacity:
by-vmSize:
Standard_NV12s.*: 5
default: 10
wp-aws:
owner: x@x
cloud: aws
..
workerManagerConfig:
initialWeight:
by-region:
us.*: 0.8
default: 1
maxCapacity:
by-instanceType:
default: 10
m.*large:
by-region:
default: 10
west-us-2: 5
wp-gcp:
owner: x@x
cloud: gcp
..
workerManagerConfig:
initialWeight:
by-region:
us-east-2: 0.8
default: 1
maxCapacity:
by-machineType:
.*c3d-standard.*: 5
default: 10
```
=> Allow overriding worker manager config per launch config

config/projects/taskcluster.yml
Testing in issue taskcluster/taskcluster#7648 is now complete, so this can be removed again. Essentially undoes #948.
=> No longer needed 

config/projects/mozci.yml
Reverts taskcluster/community-tc-config#951
The performance issues are gone, we can run this more frequently again.
=> Revert "Temporarily run mozci hooks once every 6 hours"
